v0.29.3-Update_preproc
Why:

Update CBIG_fMRI_Preproc2016

This change addresses the need by:

All

diff --git a/stable_projects/preprocessing/CBIG2022_DiffProc/TBSS/fsl_sub_torque b/stable_projects/preprocessing/CBIG2022_DiffProc/TBSS/fsl_sub_torque
--- a/stable_projects/preprocessing/CBIG2022_DiffProc/TBSS/fsl_sub_torque
+++ b/stable_projects/preprocessing/CBIG2022_DiffProc/TBSS/fsl_sub_torque
@@ -85,15 +85,15 @@ METHOD=TORQUE # method changed to TORQUE
 ## default SGE setup
 unset module
 if [ $METHOD = "SGE" ]; then
-	if [ "x$SGE_ROOT" = "x" ] ; then
-		METHOD=NONE
-	else
-		QCONF=`which qconf`
-		if [ "x$QCONF" = "x" ]; then
-			METHOD=NONE
-			echo "Warning: SGE_ROOT environment variable is set but Grid Engine software not found, will run locally" >&2
-		fi
-	fi
+    if [ "x$SGE_ROOT" = "x" ] ; then
+        METHOD=NONE
+    else
+        QCONF=`which qconf`
+        if [ "x$QCONF" = "x" ]; then
+            METHOD=NONE
+            echo "Warning: SGE_ROOT environment variable is set but Grid Engine software not found, will run locally" >&2
+        fi
+    fi
 fi
 
 # stop submitted scripts from submitting jobs themselves
@@ -103,7 +103,7 @@ if [ "X$FSLSUBALREADYRUN" = "Xtrue" ] ; then
 fi
 
 if [ "X$METHOD" = "XNONE" ]; then
-	QCONF=echo
+    QCONF=echo
 fi
 FSLSUBALREADYRUN=true
 export FSLSUBALREADYRUN
@@ -121,13 +121,13 @@ export FSLSUBALREADYRUN
 map_qname ()
 {
     if [ $1 -le 20 ] ; then
-	queue=veryshort.q
+        queue=veryshort.q
     elif [ $1 -le 120 ] ; then
-	queue=short.q
+        queue=short.q
     elif [ $1 -le 1440 ] ; then
-	queue=long.q
+        queue=long.q
     else
-	queue=verylong.q
+        queue=verylong.q
     fi
     queueCmd=" -q $queue " 
 
@@ -283,24 +283,24 @@ while [ $1 != -- ] ; do
       queueCmd=" -q $queue " 
       $QCONF -sq $queue >/dev/null 2>&1
       if [ $? -eq 1 ]; then
-	  echo "Invalid queue specified!"
-	  exit 127
+          echo "Invalid queue specified!"
+          exit 127
       fi
       shift;;
     -a)
       acceptable_arch=no
       available_archs=`qhost | tail -n +4 | awk '{print $2}' | sort | uniq`
       for a in $available_archs; do
-	if [ $2 = $a ] ; then
-	  acceptable_arch=yes
-	fi
+    if [ $2 = $a ] ; then
+      acceptable_arch=yes
+    fi
       done
       if [ $acceptable_arch = yes ]; then
-	  sge_arch="-l arch=$2"
+          sge_arch="-l arch=$2"
       else
-	  echo "Sorry arch of $2 is not supported on this SGE configuration!"
-	  echo "Should be one of:" $available_archs
-	  exit 127
+          echo "Sorry arch of $2 is not supported on this SGE configuration!"
+          echo "Should be one of:" $available_archs
+          exit 127
       fi
       shift;;
     -p)
@@ -316,14 +316,14 @@ while [ $1 != -- ] ; do
     -t)
       taskfile=$2
       if [ -f "$taskfile" ] ; then
-	      tasks=`wc -l $taskfile | awk '{print $1}'`
-	      if [ $tasks -ne 0 ]; then
-    	  	sge_tasks="-t 1-$tasks"
-    	  else
-    	    echo "Task file ${taskfile} is empty"
-    	    echo "Should be a text file listing all the commands to run!"
-    	    exit -1
-    	  fi
+          tasks=`wc -l $taskfile | awk '{print $1}'`
+          if [ $tasks -ne 0 ]; then
+              sge_tasks="-t 1-$tasks"
+          else
+            echo "Task file ${taskfile} is empty"
+            echo "Should be a text file listing all the commands to run!"
+            exit -1
+          fi
       else
           echo "Task file (${taskfile}) does not exist"
           exit -1
@@ -335,7 +335,7 @@ while [ $1 != -- ] ; do
     -R)
       RAM="-l mem_free=${2}M"
       if [[ $METHOD = "TORQUE" ]] ; then # modified mem options
-   	RAM="${2}GB"
+          RAM="${2}GB"
       fi 
       shift;;
     -m)
@@ -345,13 +345,13 @@ while [ $1 != -- ] ; do
       LogOpts="-o $2 -e $2";
       LogDir="${2}/";
       if [ ! -e ${2} ]; then 
-	  mkdir -p $2
+          mkdir -p $2
       else
-	  echo ${2} | grep '/dev/null' >/dev/null 2>&1
-	  if [ $? -eq 1 ] && [ -f ${2} ]; then
-	      echo "Log destination is a file (should be a folder)"
-	      exit -1
-	  fi
+      echo ${2} | grep '/dev/null' >/dev/null 2>&1
+      if [ $? -eq 1 ] && [ -f ${2} ]; then
+          echo "Log destination is a file (should be a folder)"
+          exit -1
+      fi
       fi
       shift;;
     -F)
@@ -375,23 +375,23 @@ shift
 ###########################################################################
 
 if [ -z "$taskfile" ] && [ -z "$1" ]; then
-	echo "Either supply a command to run or a parallel task file"
-	exit -1
+    echo "Either supply a command to run or a parallel task file"
+    exit -1
 fi
 
 if [ -z "$taskfile" ] && [ ! -x "$1" ]; then
-	which $1 >/dev/null 2>&1
-	if [ $? -ne 0 ]; then
-		echo "The command you have requested cannot be found or is not executable"
-		exit -1
-	fi
+    which $1 >/dev/null 2>&1
+    if [ $? -ne 0 ]; then
+        echo "The command you have requested cannot be found or is not executable"
+        exit -1
+    fi
 fi
 
 if [ "x$JobName" = x ] ; then 
     if [ "x$taskfile" != x ] ; then
-	JobName=`basename $taskfile`
+        JobName=`basename $taskfile`
     else
-	JobName=`basename $1`
+        JobName=`basename $1`
     fi
 fi
 
@@ -406,7 +406,7 @@ if [ "x$peName" != "x" ]; then
     
     if [ "X$peName" = "X$omp_pe" ]; then
         OMP_NUM_THREADS=$peThreads
-	export OMP_NUM_THREADS
+        export OMP_NUM_THREADS
     fi
 
 fi
@@ -424,57 +424,57 @@ case $METHOD in
        ###########################################################################
        # Test Parallel environment options
        ###########################################################################
-	if [ "x$peName" != x ]; then
+    if [ "x$peName" != x ]; then
             # Is this a configured PE?
 
-	    $QCONF -sp $peName >/dev/null 2>&1
+        $QCONF -sp $peName >/dev/null 2>&1
 
-	    if [ $? -eq 1 ]; then
-		echo $@
-		echo "$peName is not a valid PE"
-		exit -1
-	    fi
+        if [ $? -eq 1 ]; then
+            echo $@
+            echo "$peName is not a valid PE"
+            exit -1
+        fi
 
             # Get a list of queues configured for this PE and confirm that the queue
             # we have submitted to has that PE set up.
-	    qstat -g c -pe $peName >/dev/null 2>&1
-	    if [ $? -eq 1 ]; then
-		echo "No parallel environments configured!"
-		exit -1
-	    fi
+        qstat -g c -pe $peName >/dev/null 2>&1
+        if [ $? -eq 1 ]; then
+            echo "No parallel environments configured!"
+            exit -1
+        fi
 
-	    qstat -g c -pe $peName | sed '1,2d' | awk '{ print $1 }' | grep ^$queue >/dev/null 2>&1
+        qstat -g c -pe $peName | sed '1,2d' | awk '{ print $1 }' | grep ^$queue >/dev/null 2>&1
 
-	    if [ $? -eq 1 ]; then
-		echo $@
-		echo "PE $peName is not configured on $queue"
-		exit -1
-	    fi
+        if [ $? -eq 1 ]; then
+            echo $@
+            echo "PE $peName is not configured on $queue"
+            exit -1
+        fi
 
-	    # The -w e option will result in the job failing if there are insufficient slots
+        # The -w e option will result in the job failing if there are insufficient slots
             # on any of the cluster nodes
-	    pe_options="-pe $peName $peThreads -w e"
+        pe_options="-pe $peName $peThreads -w e"
 
-	fi
+    fi
 
-	if [ "x$tasks" = "x" ] ; then
-	    if [ $scriptmode -ne 1 ] ; then
-		sge_command="qsub -V -cwd -shell n -b y -r y $queueCmd $pe_options -M $mailto -N $JobName -m $MailOpts $LogOpts $sge_arch $RAM $sge_hold"
-	    else
-		sge_command="qsub $LogOpts $sge_arch $sge_hold"
-	    fi
-	    if [ $verbose -eq 1 ] ; then 
-		echo sge_command: $sge_command >&2
-		echo executing: $@ >&2
-	    fi
-	    exec $sge_command $@ | awk '{print $3}'
-	else
-	    sge_command="qsub -V -cwd $queueCmd $pe_options -M $mailto -N $JobName -m $MailOpts $LogOpts $sge_arch $RAM $sge_hold $sge_tasks"
-	    if [ $verbose -eq 1 ] ; then 
-		echo sge_command: $sge_command >&2
-		echo control file: $taskfile >&2
-	    fi
-	    exec $sge_command <<EOF | awk '{print $3}' | awk -F. '{print $1}'
+    if [ "x$tasks" = "x" ] ; then
+        if [ $scriptmode -ne 1 ] ; then
+            sge_command="qsub -V -cwd -shell n -b y -r y $queueCmd $pe_options -M $mailto -N $JobName -m $MailOpts $LogOpts $sge_arch $RAM $sge_hold"
+        else
+            sge_command="qsub $LogOpts $sge_arch $sge_hold"
+        fi
+        if [ $verbose -eq 1 ] ; then 
+            echo sge_command: $sge_command >&2
+            echo executing: $@ >&2
+        fi
+        exec $sge_command $@ | awk '{print $3}'
+    else
+        sge_command="qsub -V -cwd $queueCmd $pe_options -M $mailto -N $JobName -m $MailOpts $LogOpts $sge_arch $RAM $sge_hold $sge_tasks"
+        if [ $verbose -eq 1 ] ; then 
+            echo sge_command: $sge_command >&2
+            echo control file: $taskfile >&2
+        fi
+        exec $sge_command <<EOF | awk '{print $3}' | awk -F. '{print $1}'
 #!/bin/sh
 
 #$ -S /bin/sh
@@ -483,39 +483,39 @@ command=\`sed -n -e "\${SGE_TASK_ID}p" $taskfile\`
 
 exec /bin/sh -c "\$command"
 EOF
-	fi
-	;;
+    fi
+    ;;
 
 
 ###########################################################################
 # Schedule on TORQUE cluster
 ###########################################################################
     TORQUE)
-	echo "TORQUE processing:"
-		if [ $verbose -eq 1 ] ; then 
-			echo "Running commands in: $taskfile" >&2
-	    	fi
+    echo "TORQUE processing:"
+        if [ $verbose -eq 1 ] ; then 
+                echo "Running commands in: $taskfile" >&2
+            fi
 
-	    	n=1
-		while [ $n -le $tasks ] ; do
-			# get command from taskfile
-			line=`sed -n -e ''${n}'p' $taskfile`
-			if [ $verbose -eq 1 ] ; then 
-			    echo executing: $line >&2
-			fi
+            n=1
+        while [ $n -le $tasks ] ; do
+            # get command from taskfile
+            line=`sed -n -e ''${n}'p' $taskfile`
+            if [ $verbose -eq 1 ] ; then 
+                echo executing: $line >&2
+            fi
 
-			#run command
-			logdir= $( pwd )
-			$CBIG_CODE_DIR/setup/CBIG_pbsubmit -cmd "$cmd" -walltime "$walltime" -name "$JobName" \
-				-mem "$RAM" -joberr "$logdir" -jobout "$logdir"
+            #run command
+            logdir= $( pwd )
+            $CBIG_CODE_DIR/setup/CBIG_pbsubmit -cmd "$cmd" -walltime "$walltime" -name "$JobName" \
+                -mem "$RAM" -joberr "$logdir" -jobout "$logdir"
 
-			# pause and go on to next job 
-			sleep 2
-			n=`expr $n + 1`
-		done
+            # pause and go on to next job 
+            sleep 2
+            n=`expr $n + 1`
+        done
 
-	exit 1
-	;;
+    exit 1
+    ;;
 
 
 ###########################################################################
@@ -524,38 +524,38 @@ EOF
 ###########################################################################
 
     NONE)
-	if [ "x$tasks" = "x" ] ; then
-	    if [ $verbose -eq 1 ] ; then 
-		echo executing: $@ >&2
-	    fi
+    if [ "x$tasks" = "x" ] ; then
+        if [ $verbose -eq 1 ] ; then 
+            echo executing: $@ >&2
+        fi
 
-	    /bin/sh <<EOF1 > ${LogDir}${JobName}.o$$ 2> ${LogDir}${JobName}.e$$
+        /bin/sh <<EOF1 > ${LogDir}${JobName}.o$$ 2> ${LogDir}${JobName}.e$$
 $@
 EOF1
-	    ERR=$?
-	    if [ $ERR -ne 0 ] ; then
-		cat ${LogDir}${JobName}.e$$ >&2
-		exit $ERR
-	    fi
-	else
-	    if [ $verbose -eq 1 ] ; then 
-		echo "Running commands in: $taskfile" >&2
-	    fi
+        ERR=$?
+        if [ $ERR -ne 0 ] ; then
+            cat ${LogDir}${JobName}.e$$ >&2
+            exit $ERR
+        fi
+    else
+        if [ $verbose -eq 1 ] ; then 
+            echo "Running commands in: $taskfile" >&2
+        fi
 
-	    n=1
-	    while [ $n -le $tasks ] ; do
-		line=`sed -n -e ''${n}'p' $taskfile`
-		if [ $verbose -eq 1 ] ; then 
-		    echo executing: $line >&2
-		fi
-		/bin/sh <<EOF2 > ${LogDir}${JobName}.o$$.$n 2> ${LogDir}${JobName}.e$$.$n
+        n=1
+        while [ $n -le $tasks ] ; do
+        line=`sed -n -e ''${n}'p' $taskfile`
+        if [ $verbose -eq 1 ] ; then 
+            echo executing: $line >&2
+        fi
+        /bin/sh <<EOF2 > ${LogDir}${JobName}.o$$.$n 2> ${LogDir}${JobName}.e$$.$n
 $line
 EOF2
-		n=`expr $n + 1`
-	    done
-	fi	
-	echo $$
-	;;
+        n=`expr $n + 1`
+        done
+    fi
+    echo $$
+    ;;
 
 esac
 
diff --git a/stable_projects/preprocessing/CBIG2022_DiffProc/TBSS/tbss_1_preproc_torque b/stable_projects/preprocessing/CBIG2022_DiffProc/TBSS/tbss_1_preproc_torque
--- a/stable_projects/preprocessing/CBIG2022_DiffProc/TBSS/tbss_1_preproc_torque
+++ b/stable_projects/preprocessing/CBIG2022_DiffProc/TBSS/tbss_1_preproc_torque
@@ -89,23 +89,23 @@ jobname='tbss_1_mask'
 
 # exit if no files
 if [ $jobs2run -eq 1 ] && [ $@ == '*.nii.gz' ]; then
-	echo "WARNING: No files for tbss step 1, SKIPPING..."
-	exit 1
+    echo "WARNING: No files for tbss step 1, SKIPPING..."
+    exit 1
 fi
 
 # exit if tbss directory and script directory not set up
 if [ ! -d "$tbssdir" ] || [ ! -d "$scriptdir" ]; then
-	echo "ERROR: tbss directory and/or script directory not found..."
-	exit 1
+    echo "ERROR: tbss directory and/or script directory not found..."
+    exit 1
 fi
 
 for f in `$FSLDIR/bin/imglob $subs` ; do
-	# check if FA file exists - if it does do not run
-	if [ -e $tbssdir/FA/${f}_FA.nii.gz ]; then
-		echo "$f exists: skipping processing"
-	else
-		$scriptdir/tbss_1_mask $f $tbssdir
-	fi
+    # check if FA file exists - if it does do not run
+    if [ -e $tbssdir/FA/${f}_FA.nii.gz ]; then
+        echo "$f exists: skipping processing"
+    else
+        $scriptdir/tbss_1_mask $f $tbssdir
+    fi
 done
 
 echo "Now running \"slicesdir\" to generate report of all input images"
diff --git a/stable_projects/preprocessing/CBIG2022_DiffProc/TBSS/tbss_2_reg_torque b/stable_projects/preprocessing/CBIG2022_DiffProc/TBSS/tbss_2_reg_torque
--- a/stable_projects/preprocessing/CBIG2022_DiffProc/TBSS/tbss_2_reg_torque
+++ b/stable_projects/preprocessing/CBIG2022_DiffProc/TBSS/tbss_2_reg_torque
@@ -88,15 +88,15 @@ do_reg(){
     f=$1
 
     for g in `$FSLDIR/bin/imglob *_FA.*` ; do
-        	
-	o=${g}_to_$f
-	wd=$(pwd) # append working directory to command file
-	if [ ! -f ${o}_warp.msf ] ; then
-	    echo $o
-	    touch ${o}_warp.msf
-	    echo "$FSLDIR/bin/fsl_reg $wd/$g $wd/$f $wd/${g}_to_$f -e -FA" >> .commands
-	fi
-	
+        
+    o=${g}_to_$f
+    wd=$(pwd) # append working directory to command file
+    if [ ! -f ${o}_warp.msf ] ; then
+        echo $o
+        touch ${o}_warp.msf
+        echo "$FSLDIR/bin/fsl_reg $wd/$g $wd/$f $wd/${g}_to_$f -e -FA" >> .commands
+    fi
+
     done
 }
 
@@ -108,27 +108,27 @@ echo [`date`] [`hostname`] [`uname -a`] [`pwd`] [$0 $@] >> .tbsslog
 
 # exit if tbss directory not set up
 if [ ! -d "$tbssdir" ]; then
-	echo "ERROR: tbss directory not found..."
-	exit 1
+    echo "ERROR: tbss directory not found..."
+    exit 1
 fi
 
 if [ $1 = -n ] ; then
     cd FA
     for f in `$FSLDIR/bin/imglob *_FA.*` ; do
-	do_reg $f
+    do_reg $f
     done
 else
     if [ $1 = -T ] ; then
-	TARGET=$FSLDIR/data/standard/FMRIB58_FA_1mm
+        TARGET=$FSLDIR/data/standard/FMRIB58_FA_1mm
     elif [ $1 = -t ] ; then
-	TARGET=$2
+        TARGET=$2
     else
-	Usage
+        Usage
     fi
     if [ `${FSLDIR}/bin/imtest $TARGET` = 0 ] ; then
-	echo ""
-	echo "Error: target image $TARGET not valid"
-	Usage
+        echo ""
+        echo "Error: target image $TARGET not valid"
+        Usage
     fi
     $FSLDIR/bin/imcp $TARGET FA/target
     cd FA
@@ -140,16 +140,16 @@ jobname='tbss_2_reg'
 jobs2run=$(cat .commands | wc -l)
 
 while IFS= read -r cmd; do
-	# extract subject names for mat files
-	matfile="$(echo $cmd | grep -oP '/FA/\K.*?(?=_FA )')_FA_to_target.mat"
-	# check if registration mat file exists - if it does do not run
-	if [ -e $matfile ]; then
-		echo "$matfile exists: skipping processing"
-	else
-		#run command
-		ssh headnode "$CBIG_CODE_DIR/setup/CBIG_pbsubmit -cmd '$cmd' -walltime 01:00:00 \
-			-name $jobname -mem 3GB -joberr '$tbssdir' -jobout '$tbssdir'" < /dev/null
-	fi
+    # extract subject names for mat files
+    matfile="$(echo $cmd | grep -oP '/FA/\K.*?(?=_FA )')_FA_to_target.mat"
+    # check if registration mat file exists - if it does do not run
+    if [ -e $matfile ]; then
+        echo "$matfile exists: skipping processing"
+    else
+        #run command
+        ssh headnode "$CBIG_CODE_DIR/setup/CBIG_pbsubmit -cmd '$cmd' -walltime 01:00:00 \
+            -name $jobname -mem 3GB -joberr '$tbssdir' -jobout '$tbssdir'" < /dev/null
+    fi
 done < .commands
 
 # wait until all jobs run: counted by username and job name
@@ -158,10 +158,10 @@ user_id=$( whoami )
 running_jobs=$( ssh headnode "qselect -u $user_id -N $jobname | wc -l" )
 start=$SECONDS
 while [ $running_jobs -gt 0 ]; do
-	duration_min=$((( $SECONDS - $start ) / 60))
-	echo "	${duration_min}m: $running_jobs jobs  still running"
-	sleep 1m
-	running_jobs=$( ssh headnode "qselect -u $user_id -N $jobname | wc -l" )
+    duration_min=$((( $SECONDS - $start ) / 60))
+    echo "    ${duration_min}m: $running_jobs jobs  still running"
+    sleep 1m
+    running_jobs=$( ssh headnode "qselect -u $user_id -N $jobname | wc -l" )
 done
 
 mkdir -p scheduler_logs
diff --git a/stable_projects/preprocessing/CBIG2022_DiffProc/TBSS/tbss_3_postreg_torque b/stable_projects/preprocessing/CBIG2022_DiffProc/TBSS/tbss_3_postreg_torque
--- a/stable_projects/preprocessing/CBIG2022_DiffProc/TBSS/tbss_3_postreg_torque
+++ b/stable_projects/preprocessing/CBIG2022_DiffProc/TBSS/tbss_3_postreg_torque
@@ -98,8 +98,8 @@ cd FA
 
 # exit if tbss directory and FA directory not set up
 if [ ! -d "$tbssdir" ] || [ ! -d "$FAdir" ] ; then
-	echo "ERROR: tbss and/or FA directory not found..."
-	exit 1
+    echo "ERROR: tbss and/or FA directory not found..."
+    exit 1
 fi
 
 /bin/rm -f all.msf
@@ -114,23 +114,23 @@ else
 
     for f in `$FSLDIR/bin/imglob *_FA.nii* *_FA.img* *_FA.hdr*` ; do
 
-	meanscore=0
-	medianscore=0
+    meanscore=0
+    medianscore=0
 
-	for g in `$FSLDIR/bin/imglob *_FA.nii* *_FA.img* *_FA.hdr*` ; do
-	
-	    thismeanscore=`cat ${g}_to_${f}_warp.msf | awk '{print $1}'`
-	    thismedianscore=`cat ${g}_to_${f}_warp.msf | awk '{print $2}'`
+    for g in `$FSLDIR/bin/imglob *_FA.nii* *_FA.img* *_FA.hdr*` ; do
 
-	    meanscore=`echo "10 k $meanscore $thismeanscore + p" | dc -`
-	    medianscore=`echo "10 k $medianscore $thismedianscore + p" | dc -`
-	done
+        thismeanscore=`cat ${g}_to_${f}_warp.msf | awk '{print $1}'`
+        thismedianscore=`cat ${g}_to_${f}_warp.msf | awk '{print $2}'`
 
-	meanscore=`echo "10 k $meanscore $n / p" | dc -`
-	medianscore=`echo "10 k $medianscore $n / p" | dc -`
+        meanscore=`echo "10 k $meanscore $thismeanscore + p" | dc -`
+        medianscore=`echo "10 k $medianscore $thismedianscore + p" | dc -`
+    done
 
-	echo "$f $meanscore $medianscore"
-	echo "$f $meanscore $medianscore" >> all.msf
+    meanscore=`echo "10 k $meanscore $n / p" | dc -`
+    medianscore=`echo "10 k $medianscore $n / p" | dc -`
+
+    echo "$f $meanscore $medianscore"
+    echo "$f $meanscore $medianscore" >> all.msf
 
     done
 
@@ -144,67 +144,67 @@ echo $best > best.msf
 
 mkdir -p ../stats
 
-	# is target already in MNI152 space? (kludge)
-	if [ `${FSLDIR}/bin/imtest target` = 1 ] && [ `$FSLDIR/bin/fslval $best dim1` = 182 ] && [ `$FSLDIR/bin/fslval $best dim2` = 218 ] && [ `$FSLDIR/bin/fslval $best dim3` = 182 ] ; then
+    # is target already in MNI152 space? (kludge)
+    if [ `${FSLDIR}/bin/imtest target` = 1 ] && [ `$FSLDIR/bin/fslval $best dim1` = 182 ] && [ `$FSLDIR/bin/fslval $best dim2` = 218 ] && [ `$FSLDIR/bin/fslval $best dim3` = 182 ] ; then
 
-	    echo "transforming all FA images into MNI152 space"
-	    filelist=`$FSLDIR/bin/imglob *_FA.nii* *_FA.img* *_FA.hdr*`;
-	    # check that all the registration results are there!
-	    missingwarps="";
-	    for f in $filelist ; do
-		if [ `${FSLDIR}/bin/imtest ${f}_to_target_warp` = 0 ] ; then
-		    missingwarps="$missingwarps ${f}_to_target_warp"
-		fi
-	    done
-	    if [ `echo $missingwarps | wc -c` -gt 1 ] ; then
-		echo "ERROR:: cannot find the following warp results:"
-		echo "    $missingwarps"
-		echo "Please wait for registration (fnirt) to finish or re-run registrations";
-		exit 1;
-	    fi
+        echo "transforming all FA images into MNI152 space"
+        filelist=`$FSLDIR/bin/imglob *_FA.nii* *_FA.img* *_FA.hdr*`;
+        # check that all the registration results are there!
+        missingwarps="";
+        for f in $filelist ; do
+        if [ `${FSLDIR}/bin/imtest ${f}_to_target_warp` = 0 ] ; then
+            missingwarps="$missingwarps ${f}_to_target_warp"
+        fi
+        done
+        if [ `echo $missingwarps | wc -c` -gt 1 ] ; then
+            echo "ERROR:: cannot find the following warp results:"
+            echo "    $missingwarps"
+            echo "Please wait for registration (fnirt) to finish or re-run registrations";
+            exit 1;
+        fi
 
-	    jobname='tbss_3_warp'
+        jobname='tbss_3_warp'
 
-	    for f in $filelist ; do
-		if [ -e "$FAdir/${f}_to_target.nii.gz" ]; then
-			echo "${f}_to_target exists: skipping processing"
-		else		
-			# run in scheduler
-			cmd="$FSLDIR/bin/applywarp -i $FAdir/$f -o $FAdir/${f}_to_target -r $FAdir/target -w $FAdir/${f}_to_target_warp --rel"
-			ssh headnode "$CBIG_CODE_DIR/setup/CBIG_pbsubmit -cmd '$cmd' -walltime 01:00:00 \
-				-name $jobname -mem 3GB -joberr '$tbssdir' -jobout '$tbssdir' "			
-			sleep 2
-		fi
-	    done
+        for f in $filelist ; do
+        if [ -e "$FAdir/${f}_to_target.nii.gz" ]; then
+            echo "${f}_to_target exists: skipping processing"
+        else
+            # run in scheduler
+            cmd="$FSLDIR/bin/applywarp -i $FAdir/$f -o $FAdir/${f}_to_target -r $FAdir/target -w $FAdir/${f}_to_target_warp --rel"
+            ssh headnode "$CBIG_CODE_DIR/setup/CBIG_pbsubmit -cmd '$cmd' -walltime 01:00:00 \
+                -name $jobname -mem 3GB -joberr '$tbssdir' -jobout '$tbssdir' "
+            sleep 2
+        fi
+        done
 
-	    # wait until all jobs run: counted by username and job name
-	    echo "Waiting for all jobs to complete before moving on..."
-	    user_id=$( whoami )
-	    running_jobs=$( ssh headnode "qselect -u $user_id -N $jobname | wc -l" )
-	    start=$SECONDS
-	    while [ $running_jobs -gt 0 ]; do
-		duration_min=$((( $SECONDS - $start ) / 60))
-		echo "	${duration_min}m: $running_jobs jobs  still running"
-		sleep 1m
-		running_jobs=$( ssh headnode "qselect -u $user_id -N $jobname | wc -l" )
-	    done
+        # wait until all jobs run: counted by username and job name
+        echo "Waiting for all jobs to complete before moving on..."
+        user_id=$( whoami )
+        running_jobs=$( ssh headnode "qselect -u $user_id -N $jobname | wc -l" )
+        start=$SECONDS
+        while [ $running_jobs -gt 0 ]; do
+            duration_min=$((( $SECONDS - $start ) / 60))
+            echo "    ${duration_min}m: $running_jobs jobs  still running"
+            sleep 1m
+            running_jobs=$( ssh headnode "qselect -u $user_id -N $jobname | wc -l" )
+        done
 
-	    mkdir -p FA/scheduler_logs
-	    mv $tbssdir/*.headnode.* $tbssdir/FA/scheduler_logs
+        mkdir -p FA/scheduler_logs
+        mv $tbssdir/*.headnode.* $tbssdir/FA/scheduler_logs
 
-	else
+    else
 
-	    echo "affine-registering target to MNI152 space"
-	    $FSLDIR/bin/fslmaths target -bin target_mask
-	    $FSLDIR/bin/flirt -in target -inweight target_mask -ref $FSLDIR/data/standard/FMRIB58_FA_1mm -omat target_to_MNI152.mat -out target_to_MNI152
+        echo "affine-registering target to MNI152 space"
+        $FSLDIR/bin/fslmaths target -bin target_mask
+        $FSLDIR/bin/flirt -in target -inweight target_mask -ref $FSLDIR/data/standard/FMRIB58_FA_1mm -omat target_to_MNI152.mat -out target_to_MNI152
 
-	    echo "transforming (and upsampling) all FA images into MNI152 space"
-	    for f in `$FSLDIR/bin/imglob *_FA.nii* *_FA.img* *_FA.hdr*` ; do
-		echo $f
-		$FSLDIR/bin/applywarp -i $f -o ${f}_to_target -r $FSLDIR/data/standard/FMRIB58_FA_1mm -w ${f}_to_${best}_warp --postmat=target_to_MNI152.mat
-	    done
+        echo "transforming (and upsampling) all FA images into MNI152 space"
+        for f in `$FSLDIR/bin/imglob *_FA.nii* *_FA.img* *_FA.hdr*` ; do
+            echo $f
+            $FSLDIR/bin/applywarp -i $f -o ${f}_to_target -r $FSLDIR/data/standard/FMRIB58_FA_1mm -w ${f}_to_${best}_warp --postmat=target_to_MNI152.mat
+        done
 
-	fi
+    fi
 
 echo "merging all upsampled FA images into single 4D image" # needs to be run in compiler
 $FSLDIR/bin/fslmerge -t ../stats/all_FA `$FSLDIR/bin/imglob *_FA_to_target.*`
diff --git a/stable_projects/preprocessing/CBIG2022_DiffProc/TBSS/tbss_non_FA_torque b/stable_projects/preprocessing/CBIG2022_DiffProc/TBSS/tbss_non_FA_torque
--- a/stable_projects/preprocessing/CBIG2022_DiffProc/TBSS/tbss_non_FA_torque
+++ b/stable_projects/preprocessing/CBIG2022_DiffProc/TBSS/tbss_non_FA_torque
@@ -92,8 +92,8 @@ fi
 
 # exit if tbss directory and FA directory not set up
 if [ ! -d "$tbssdir" ] || [ ! -d "$FAdir" ] ; then
-	echo "ERROR: tbss and/or FA directory not found..."
-	exit 1
+    echo "ERROR: tbss and/or FA directory not found..."
+    exit 1
 fi
 
 jobname='tbss_non_FA'
@@ -102,16 +102,16 @@ echo "running registration for ${ALTIM}:"
 
 for f in `$FSLDIR/bin/imglob *_FA.*` ; do
     f=` echo $f | sed 's/_FA$//g'`
-	if [ -e "$FAdir/${f}_to_target_${ALTIM}.nii.gz" ]; then
-		echo "$FAdir/${f}_to_target_${ALTIM} exists: skipping processing"
-	else
-		# run in scheduler
-	    	cmd="$FSLDIR/bin/applywarp -i $FAdir/../${ALTIM}/$f -o $FAdir/${f}_to_target_${ALTIM} -r $FSLDIR/data/standard/FMRIB58_FA_1mm -w $FAdir/${f}_FA_to_${best}_warp $postaffine "
-		#run command
-		ssh headnode "$CBIG_CODE_DIR/setup/CBIG_pbsubmit -cmd '$cmd' -walltime 01:00:00 \
-			-name $jobname -mem 3GB -joberr '$tbssdir' -jobout '$tbssdir'"		
-		sleep 2
-	fi
+    if [ -e "$FAdir/${f}_to_target_${ALTIM}.nii.gz" ]; then
+        echo "$FAdir/${f}_to_target_${ALTIM} exists: skipping processing"
+    else
+        # run in scheduler
+            cmd="$FSLDIR/bin/applywarp -i $FAdir/../${ALTIM}/$f -o $FAdir/${f}_to_target_${ALTIM} -r $FSLDIR/data/standard/FMRIB58_FA_1mm -w $FAdir/${f}_FA_to_${best}_warp $postaffine "
+        #run command
+        ssh headnode "$CBIG_CODE_DIR/setup/CBIG_pbsubmit -cmd '$cmd' -walltime 01:00:00 \
+            -name $jobname -mem 3GB -joberr '$tbssdir' -jobout '$tbssdir'"
+        sleep 2
+    fi
 done
 
 # wait until all jobs run: counted by username and job name
@@ -120,10 +120,10 @@ echo "Waiting for all jobs to complete before moving on..."
 running_jobs=$( ssh headnode "qselect -u $user_id -N $jobname | wc -l" )
 start=$SECONDS
 while [ $running_jobs -gt 0 ]; do
-	duration_min=$((( $SECONDS - $start ) / 60))
-	echo "	${duration_min}m: $running_jobs jobs  still running"
-	sleep 1m
-	running_jobs=$( ssh headnode "qselect -u $user_id -N $jobname | wc -l" )
+    duration_min=$((( $SECONDS - $start ) / 60))
+    echo "    ${duration_min}m: $running_jobs jobs  still running"
+    sleep 1m
+    running_jobs=$( ssh headnode "qselect -u $user_id -N $jobname | wc -l" )
 done
 
 mkdir -p FA/scheduler_logs
