v0.4.12 - Update Brain Parcellation Projects and Pre-push Hook
Why:

Yeo2011_fcMRI_clustering
1. Add project-specific prefix Yeo2011 for two scripts of Yeo2011_fcMRI_clustering: 1000subjects_reference/Yeo_JNeurophysiol11_SplitLabels/scripts/CBIG_DownsampleMNI1mmParcellationTo2mm.csh and 1000subjects_reference/Yeo_JNeurophysiol11_SplitLabels/scripts/CBIG_ProjectSplitLabels2MNI1mm.m, which were missing in release v0.4.10.
2. Move example subjects from $CBIG_CODE_DIR/data/example_data/${subj_ID} to $CBIG_CODE_DIR/data/example_data/Corr_HNU/${subj_ID}
3. The example subjects are re-processed by a newer version of our preprocessing pipeline (v0.4.9). Hence results in ./examples are updated.
4. Update some README.md files.

Scaefer2018_LocalGlobal
1. Move example subjects from $CBIG_CODE_DIR/data/example_data/${subj_ID} to $CBIG_CODE_DIR/data/example_data/Corr_HNU/${subj_ID}.
2. The example subjects are re-processed by a newer version of our preprocessing pipeline (v0.4.9). Hence results in ./Code/examples are updated.
3. Update some README.md files.

Pre-push hook:
1. Add checking for unit_tests folder in each stable project.
2. Remove exclusion for Scaefer2018_LocalGlobal, Yeo2011_fcMRI_clustering, Liegeois2017_Surrogates projects.

This change addresses the need by:

* All users

diff --git a/hooks/pre-push b/hooks/pre-push
--- a/hooks/pre-push
+++ b/hooks/pre-push
@@ -238,7 +238,7 @@ echo "  [PASSED]"
 # 4.  (files in stable_projects/xxx/xxx (exclude Thomas, Alex, Gia, Xiuming, Raphael))[.m, .c, .cpp, .sh, .csh, .py, .pl, .r]
 ######
 EXTENSIONS_TO_CHECK=("m" "c" "cpp" "sh" "csh" "py" "pl" "r")
-EXCLUDED_DIRECTORIES=("Yeo2011_fcMRI_clustering" "Schaefer2018_LocalGlobal" "Zhang2016_ADFactors" "Liegeois2017_Surrogates")
+EXCLUDED_DIRECTORIES=("Zhang2016_ADFactors")
 
 echo -e "\n==> [Check 4] Checking stable_projects/xxx/xxx"
 for project_path in $CBIG_CODE_DIR/stable_projects/*/*
@@ -358,6 +358,18 @@ tested to work."
         fi
         echo "    [PASSED]"
     fi
+
+    ###
+    # check whether all projects have the unit_tests folder
+    ###
+    echo -e "\n====> Check whether this project has unit_tests folder"
+    if [ ! -d "$project_path/unit_tests" ]; then
+        echo "    [FAILED] $project_path does not have a unit_tests folder"
+        echo "Please add a unit_tests folder under $project_path manually"
+        exit 1
+    fi
+    echo "    [PASSED]"
+ 
 done
 exit 0
 
