v0.4.7-reconfig_CBIG_repo
Why:

1. Reorganize the external_packages/matlab to be default and non_default folders
2. Update CBIG_sample_config.sh to use startup.m in $CBIG_CODE_DIR/setup
3. Update pre-commit and pre-push hooks to check code format and config folder in preprocessing stable project
4. Remove all unused files

This change addresses the need by:

* All users

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -5,74 +5,79 @@
 ###
 if [ "$(git symbolic-ref HEAD 2>/dev/null)" == "refs/heads/master" ]
 then
-  passed=true
-  if [ -d "$CBIG_CODE_DIR/unstable_projects" ]; then
-    echo "'unstable_projects' folder exists"
-    passed=false
-  fi
-  
-  if [ -d "$CBIG_CODE_DIR/legacy" ]; then
-    echo "'legacy' folder exists"
-    passed=false
-  fi
-  
-  if [ -d "$CBIG_CODE_DIR/developers" ]; then
-    echo "'developers' folder exists"
-    passed=false
-  fi
+    passed=true
+    if [ -d "$CBIG_CODE_DIR/unstable_projects" ]; then
+        echo "'unstable_projects' folder exists"
+        passed=false
+    fi
 
-  if [ "$passed" != "true" ]; then
-    echo "Committing to 'master' branch is stopped"
-    exit 1
-  fi
+    if [ -d "$CBIG_CODE_DIR/legacy" ]; then
+        echo "'legacy' folder exists"
+        passed=false
+    fi
+
+    if [ -d "$CBIG_CODE_DIR/developers" ]; then
+        echo "'developers' folder exists"
+        passed=false
+    fi
+
+    if [ "$passed" != "true" ]; then
+        echo "Committing to 'master' branch is stopped"
+        exit 1
+    fi
 fi
 
+######
+# 1. (committed files)[.m, .c, .cpp, .sh, .csh, .py, .pl, .r]{stable_projects, utilities, data}
+######
 ###
-# Define the files that we want to check 
+# Find the committed files that we want to check 
 ###
+files_to_be_committed=($(git diff --cached --name-status | awk '(($1 != "D") && ($1 != "U")) { print $2 }'))
+
 EXTENSIONS_TO_CHECK=("m" "c" "cpp" "sh" "csh" "py" "pl" "r")
-DIRECTORIES_TO_CHECK=("stable_projects" "utilities")
+DIRECTORIES_TO_CHECK=("stable_projects" "utilities" "data")
 EXCLUDED_FILES=("Surf2SurfGui.m" "Vol2SurfGui.m" "CBIG_tested_config.sh" "CBIG_tested_config.csh")
-PREFIX="CBIG_"
-files_to_be_committed=($(git diff --cached --name-status | awk '(($1 != "R") && ($1 != "D") && ($1 != "U")) { print $2 }'))
 
 ###
 # Check whether committed files have the 'CBIG_' prefix 
 ###
-echo -e "\n==> Checking $PREFIX prefix of files to be committed.."
+PREFIX="CBIG_"
+echo -e "\n==> [Check] Checking that committed files have $PREFIX prefix.."
+
 all_with_valid_prefixes=1
-file_in_exclude=0
 for file_path in "${files_to_be_committed[@]}"
 do
-	file_name=$(basename $file_path)
-	for excluded_file in "${EXCLUDED_FILES[@]}"
-	do
-	    if [[ $file_name == $excluded_file ]]; then
-	      file_in_exclude=1
-	      break
-	    fi
-	done
-	if [ $file_in_exclude == 1 ]; then
-		echo "$file_name will not be checked for $PREFIX prefix"
-		break
-	fi
+    file_in_exclude=0
+    file_name=$(basename $file_path)
+    for excluded_file in "${EXCLUDED_FILES[@]}"
+    do
+        if [[ $file_name == $excluded_file ]]; then
+            file_in_exclude=1
+            break
+        fi
+    done
+    if [ $file_in_exclude == 1 ]; then
+        echo "$file_name will not be checked for $PREFIX prefix"
+        continue
+    fi
     for directory in "${DIRECTORIES_TO_CHECK[@]}"
     do 
-	    if [[ $file_path == $directory/* ]] || [[ $file_path == $file_name ]]; then
-	        for ext in "${EXTENSIONS_TO_CHECK[@]}"
-	        do
-		        if [[ $file_name != $PREFIX* ]] && [[ $file_name == *.$ext ]]; then
-		            all_with_valid_prefixes=0
-		            echo "$file_path does not have a $PREFIX prefix, please fix it manually."
-		        fi
-	        done
-	    fi
+        if [[ $file_path == $directory/* ]] || [[ $file_path == $file_name ]]; then
+            for ext in "${EXTENSIONS_TO_CHECK[@]}"
+            do
+                if [[ $file_name != $PREFIX* ]] && [[ $file_name == *.$ext ]]; then
+                    all_with_valid_prefixes=0
+                    echo "$file_path does not have a $PREFIX prefix, please fix it manually."
+                fi
+            done
+        fi
     done
 done
 
 if [ $all_with_valid_prefixes == 0 ]; then
-  echo "   [FAILED] There are functions without $PREFIX prefix. Abort committing."
-  exit 1
+    echo "   [FAILED] There are functions without $PREFIX prefix. Abort committing."
+    exit 1
 fi
 echo "   [PASSED]"
 
@@ -81,44 +86,44 @@ echo "   [PASSED]"
 ###
 mit_license="Written by [your name] and CBIG under MIT license: https://github.com/ThomasYeoLab/CBIG/blob/master/LICENSE.md"
 all_with_license=1
-file_in_exclude=0
-echo -e "\n==> Checking MIT license of files to be committed.."
+echo -e "\n==> [Check] Checking that committed files have MIT license.."
 for file_path in "${files_to_be_committed[@]}"
 do
+    file_in_exclude=0
     file_name=$(basename $file_path)
-	for excluded_file in "${EXCLUDED_FILES[@]}"
-	do
-	    if [[ $file_name == $excluded_file ]]; then
-	      file_in_exclude=1
-	      break
-	    fi
-	done
-	if [ $file_in_exclude == 1 ]; then
-		echo "$file_name will not be checked for MIT license"
-		break
-	fi
-	for directory in "${DIRECTORIES_TO_CHECK[@]}"
-	do
-	    if [[ $file_path == $directory/* ]] || [[ $file_path == $file_name ]]; then
-	    	for ext in "${EXTENSIONS_TO_CHECK[@]}"
-	      	do
-	      		if [[ $file_name = *.$ext ]]; then
-	      			license_line=`grep "MIT license" $file_path`
-	      			if [[ "$license_line" == "" ]]; then
-	      				all_with_license=0
-	      				echo "$file_path does not have a MIT license"
-	      			elif [[ "$license_line" == *"CBIG under MIT license: https://github.com/ThomasYeoLab/CBIG/blob/master/LICENSE.md" && "$license_line" == *"Written by"* ]]; then
-	      				# do nothing
-	      				:
-	      			else
-	      				all_with_license=0
-	      				echo "$file_path does not follow our MIT license format: "
-	      				echo "$mit_license"
-	      			fi
-	      		fi
-		    done
-	    fi
-	done
+    for excluded_file in "${EXCLUDED_FILES[@]}"
+    do
+        if [[ $file_name == $excluded_file ]]; then
+            file_in_exclude=1
+            break
+        fi
+    done
+    if [ $file_in_exclude == 1 ]; then
+        echo "$file_name will not be checked for MIT license"
+        continue
+    fi
+    for directory in "${DIRECTORIES_TO_CHECK[@]}"
+    do
+        if [[ $file_path == $directory/* ]] || [[ $file_path == $file_name ]]; then
+            for ext in "${EXTENSIONS_TO_CHECK[@]}"
+            do
+                if [[ $file_name = *.$ext ]]; then
+                    license_line=`grep "MIT license" $file_path`
+                    if [[ "$license_line" == "" ]]; then
+                        all_with_license=0
+                        echo "$file_path does not have a MIT license"
+                    elif [[ "$license_line" == *"CBIG under MIT license: https://github.com/ThomasYeoLab/CBIG/blob/master/LICENSE.md" && "$license_line" == *"Written by"* ]]; then
+                        # do nothing
+                        :
+                    else
+                        all_with_license=0
+                        echo "$file_path does not follow our MIT license format: "
+                        echo "$mit_license"
+                    fi
+                fi
+            done
+        fi
+    done
 done
 
 if [ $all_with_license == 0 ]; then
@@ -130,41 +135,105 @@ if [ $all_with_license == 0 ]; then
 fi
 echo "   [PASSED]"
 
+######
+# 2. (committed files)[.m]{stable_projects, utilities, data}
+######
+files_to_be_committed=($(git diff --cached --name-status | awk '(($1 != "D") && ($1 != "U")) { print $2 }'))
+
+EXTENSIONS_TO_CHECK=("m")
+DIRECTORIES_TO_CHECK=("stable_projects" "utilities" "data")
+EXCLUDED_FILES=("Surf2SurfGui.m" "Vol2SurfGui.m" "CBIG_tested_config.sh" "CBIG_tested_config.csh" "tested_startup.m")
+
 ###
-# check whether each project subfolder contains a "CBIG_tested_config.sh" or "CBIG_tested_config.csh" file
+# If a matlab function has addpath(xxx) at the begining, check whether it has rmpath(xxx) in the end
 ###
-echo -e "\n==> Checking CBIG_tested_config files of each project.."
-all_with_config=1
-for subfolder in $CBIG_CODE_DIR/stable_projects/*/*
+all_with_valid_rmpath=1
+echo -e "\n==> [Check] If you 'addpath' at the begining of a matlab function, check 'rmpath' at the end.."
+for file_path in "${files_to_be_committed[@]}"
 do
-	if [[ ! -e $subfolder/CBIG_tested_config.sh ]] && [[ ! -e $subfolder/CBIG_tested_config.csh ]]; then
-		all_with_config=0
-		echo "$subfolder does not have a CBIG_tested_config file"
-    else 
-        if [[ -e $subfolder/CBIG_tested_config.sh ]]; then
-            secondline=`sed -n 2p $subfolder/CBIG_tested_config.sh`
-            if [[ "$secondline" != "# Last successfully run on"* ]]; then
-                all_with_config=0
-                echo "$subfolder/CBIG_tested_config.sh does not have the time stamp"
-            fi
-        elif [[ -e $subfolder/CBIG_tested_config.csh ]]; then
-            secondline=`sed -n 2p $subfolder/CBIG_tested_config.csh`
-            if [[ "$secondline" != "# Last successfully run on"* ]]; then
-                all_with_config=0
-                echo "$subfolder/CBIG_tested_config.csh does not have the time stamp"
-            fi
+    file_in_exclude=0
+    file_name=$(basename $file_path)
+    for excluded_file in "${EXCLUDED_FILES[@]}"
+    do
+        if [[ "$file_name" == *"$excluded_file"* ]]; then
+            file_in_exclude=1
+            break
         fi
-	fi
+    done
+    if [ $file_in_exclude == 1 ]; then
+        echo "$file_name will not be checked for rmpath"
+        continue
+    fi
+    for directory in "${DIRECTORIES_TO_CHECK[@]}"
+    do 
+        if [[ $file_path == $directory/* ]] || [[ $file_path == $file_name ]]; then
+            for ext in "${EXTENSIONS_TO_CHECK[@]}"
+            do
+                if [[ $file_name == *.$ext ]]; then
+                    tmpfile=$(mktemp)
+                    grep addpath $file_path > $tmpfile
+                    while read addpath_match
+                    do
+                        rmpath_line=${addpath_match//addpath/rmpath}
+                        rmpath_match=(`grep "$rmpath_line" $file_path`)
+                        if [[ "$rmpath_match" == "" ]]; then
+                            all_with_valid_rmpath=0
+                            echo "$file_path does not have a '$rmpath_line' at the end, please fix it manually."
+                        fi
+                    done < $tmpfile
+                    rm $tmpfile
+                fi
+            done
+        fi
+    done
 done
-if [ $all_with_config == 0 ]; then
-    echo "	  [FAILED] There are stable_projects without CBIG_tested_config files or these files do not have time stamp."
-	echo "Please add CBIG_tested_config.sh or CBIG_tested_config.csh to all stable_projects/*/* manually"
-	echo "Each stable project should contain a repo config file that was used when the project was last tested to work."
-	echo "The second line of the config file should be a comment:"
-	echo "# Last successfully run on <spelled out date to reduce confusion, e.g., Jan 7th, 2017>"
-	exit 1
+
+if [ $all_with_valid_rmpath == 0 ]; then
+    echo "   [FAILED] There are functions without 'rmpath' at the end. Abort committing."
+    exit 1
 fi
 echo "   [PASSED]"
+
+######
+# 3. (folders of committed files)[@xxx]{stable_projects, utilities, data}
+######
+files_to_be_committed=($(git diff --cached --name-status | awk '(($1 != "D") && ($1 != "U")) { print $2 }'))
+
+# find the folders of comitted files
+cnt=${#files_to_be_committed[@]}
+for ((i=0;i<cnt;i++))
+do
+    folders_to_be_committed[i]=$(dirname ${files_to_be_committed[i]})
+done
+unique_folders_to_be_committed=$(echo ${folders_to_be_committed[@]} | tr ' ' '\n' | sort -u | tr '\n' ' ')
+
+DIRECTORIES_TO_CHECK=("stable_projects" "utilities" "data")
+
+###
+# check whether matlab classes have CBIG_ prefix
+###
+PREFIX="CBIG_"
+echo -e "\n==> [Check] Checking that matlab classes have $PREFIX prefix.."
+
+all_with_valid_prefixes=1
+for folder in "${folders_to_be_committed[@]}"
+do
+    for directory in "${DIRECTORIES_TO_CHECK[@]}"
+    do
+        if [[ $folder == $directory/* ]] && [[ $folder == *@* ]]; then
+            if [[ $folder != *@${PREFIX}* ]]; then
+                all_with_valid_prefixes=0
+                echo "Matlab class $folder does not have a $PREFIX prefix, please fix it manually." 
+            fi
+        fi
+    done
+done
+if [ $all_with_valid_prefixes == 0 ]; then
+    echo "   [FAILED] There are Matlab classes without $PREFIX prefix. Abort committing."
+    exit 1
+fi
+echo "   [PASSED]"
+
 
 git add .
 
diff --git a/hooks/pre-push b/hooks/pre-push
--- a/hooks/pre-push
+++ b/hooks/pre-push
@@ -1,4 +1,365 @@
 #!/bin/sh
 
-# check whether changed functions will influence other functions in our repo
-$CBIG_CODE_DIR/setup/CBIG_check_changed_functions_in_other_functions.sh
+###
+# Ask the user whether he wants to continue or not
+###
+function push_or_not() {
+    read -r -p "==> Do you still want to continue pushing current branch?[y/n]" response </dev/tty
+    if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]; then
+        echo "[PASSED]"
+    else
+        echo "[FAILED] Abort pushing."
+        exit 1
+    fi
+}
+
+######
+# 1. (different files between upstream/develop and current branch)[.m, .sh, .csh]{utilities, stable_projects, data}
+######
+###
+# Find the files that we want to check
+###
+curr_branch=$(git rev-parse --abbrev-ref HEAD)
+files_to_be_checked=($(git diff --name-status upstream/develop..$curr_branch | awk '(($1 != "D") && ($1 != "U")) { print $2 }'))
+
+EXTENSIONS_TO_CHECK=("m" "sh" "csh")
+DIRECTORIES_TO_CHECK=("utilities" "stable_projects" "data")
+EXCLUDED_FILES=("Surf2SurfGui.m" "Vol2SurfGui.m" "CBIG_tested_config.sh" "CBIG_tested_config.csh")
+
+###
+# Check whether function CBIG_xxx has been used in other functions
+###
+echo -e "\n==> [Check 1] Checking whether function CBIG_xxx has been used in other functions"
+for file_path in "${files_to_be_checked[@]}"
+do
+    file_name=( $(basename "$file_path") )
+
+    # check whether file should be excluded
+    file_in_excluded=0
+    for excluded_file in "${EXCLUDED_FILES[@]}"
+    do
+        if [[ $file_name == $excluded_file ]]; then
+          file_in_excluded=1
+          break
+        fi
+    done
+    if [[ $file_in_excluded == 1 ]]; then
+        continue
+    fi
+
+    for ext in "${EXTENSIONS_TO_CHECK[@]}"
+    do
+        for directory in "${DIRECTORIES_TO_CHECK[@]}"
+        do
+            if [[ $file_path == $directory/* ]] && [[ $file_name == *.$ext ]]; then
+                echo -e "\n  ==> Checking $file_path"
+                $CBIG_CODE_DIR/setup/check_function_format/CBIG_check_whether_function_used_in_other_functions_wrapper.sh \
+                $file_path silent
+            fi
+        done
+    done
+done
+echo "  [DONE]"
+
+###
+# comments about replacing function name
+###
+echo -e "\n==> [Useful function] Replace old function name with new function name"
+echo "If you have renamed a function and want to change all instances of old function to the new function, you can use: "
+echo "setup/replace_old_with_new_func_name/CBIG_replace_old_with_new_function_name_wrapper.sh"
+echo ""
+
+###
+# Ask the user whether he wants to continue or not
+###
+push_or_not
+
+######
+# 2.  (different files between upstream/develop and current branch)[.m, .sh, .csh]
+# {utilities, stable_projects, data, external_packages(exclude class folder @xxx)}
+######
+curr_branch=$(git rev-parse --abbrev-ref HEAD)
+unset files_to_be_checked
+files_to_be_checked=($(git diff --name-status upstream/develop..$curr_branch | awk '(($1 != "D") && ($1 != "U")) { print $2 }'))
+
+EXTENSIONS_TO_CHECK=("m" "sh" "csh")
+DIRECTORIES_TO_CHECK=("utilities" "stable_projects" "data" "external_packages")
+EXCLUDED_FILES=("Surf2SurfGui.m" "Vol2SurfGui.m" "CBIG_tested_config.sh" "CBIG_tested_config.csh")
+
+TARGET_DIRECTORIES=("utilities" "stable_projects" "data" "external_packages")
+
+###
+# Check whether function name xxx has conflict with other function names
+###
+echo -e "\n==> [Check 2] Checking whether function name xxx has conflict with other function names"
+for file_path in "${files_to_be_checked[@]}"
+do
+    file_name=( $(basename "$file_path") )
+    filename_with_conflict=0
+    file_in_nondefault=0
+
+    # check whether file should be excluded
+    file_in_excluded=0
+    for excluded_file in "${EXCLUDED_FILES[@]}"
+    do
+        if [[ $file_name == $excluded_file ]]; then
+          file_in_excluded=1
+          break
+        fi
+    done
+    if [[ $file_in_excluded == 1 ]]; then
+        continue
+    fi
+
+    for ext in "${EXTENSIONS_TO_CHECK[@]}"
+    do
+        for directory in "${DIRECTORIES_TO_CHECK[@]}"
+        do
+            if [[ $file_path == $directory/* && $file_name == *.$ext && \
+                $file_path != *@* && $file_path != *matlab_bgl_mac64* ]]; then
+                echo -e "\n  ==> Checking $file_path"
+                # find all matches of filename
+                all_matches=""
+                i=0
+                for target_dir in "${TARGET_DIRECTORIES[@]}"
+                do
+                    i=$((i+1))
+                    matches=$(find $CBIG_CODE_DIR/$target_dir -name "$file_name" ! \
+                    -samefile $CBIG_CODE_DIR/$file_path ! -path "*/@*/*" ! -path "*/matlab_bgl_mac64/*")
+                    if [[ $matches ]]; then
+                        if [ $i == 1 ]; then
+                            all_matches="$matches"
+                        else
+                            all_matches="$all_matches $matches"
+                        fi
+                    fi
+                done
+
+                if [[ ${all_matches} ]]; then
+                    # check all matches
+                    for match in "${all_matches[@]}"
+                    do
+                        if [[ $match != */non_default_packages/* ]] && [[ $file_path != */non_default_packages/* ]]; then
+                            filename_with_conflict=1 
+                        fi
+                        if [[ $match == */non_default_packages/* ]] || [[ $file_path == */non_default_packages/* ]]; then
+                            file_in_nondefault=1 
+                        fi
+                        echo "$match"
+                    done
+                    if [[ $filename_with_conflict == 1 ]]; then
+                        echo "[FAILED] Abort pushing."
+                        exit 1
+                    fi
+                    if [[ $file_in_nondefault == 1 ]]; then
+                        echo "[WARNING] The user should discuss with the admin about how to handle the conflicts."
+                        push_or_not
+                    fi
+                fi
+            fi
+        done
+    done
+done
+echo "  [PASSED]"
+
+######
+# 3.  (folders of different files between upstream/develop and current branch)[@xxx]
+# {utilities, stable_projects, data, external_packages}
+######
+curr_branch=$(git rev-parse --abbrev-ref HEAD)
+unset files_to_be_checked
+files_to_be_checked=($(git diff --name-status upstream/develop..$curr_branch | awk '(($1 != "D") && ($1 != "U")) { print $2 }'))
+
+DIRECTORIES_TO_CHECK=("utilities" "stable_projects" "data" "external_packages")
+TARGET_DIRECTORIES=("utilities" "stable_projects" "data" "external_packages")
+
+# find the folders of comitted files
+cnt=${#files_to_be_checked[@]}
+for ((i=0;i<cnt;i++))
+do
+    folders_to_be_checked[i]=$(dirname ${files_to_be_checked[i]})
+done
+unique_folders_to_be_checked=($(echo ${folders_to_be_checked[@]} | tr ' ' '\n' | sort -u | tr '\n' ' '))
+
+###
+# Check whether class name @xxx has conflict with other class names
+###
+echo -e "\n==> [Check 3] Checking whether Matlab class name @xxx has conflict with other class names"
+for folder_path in "${unique_folders_to_be_checked[@]}"
+do
+    folder_name=( $(basename "$folder_path") )
+    classname_with_conflict=0
+    class_in_nondefault=0
+
+    for directory in "${DIRECTORIES_TO_CHECK[@]}"
+    do
+        if [[ $folder_path == $directory/* ]] && [[ $folder_name == @* ]]; then
+            echo -e "\n  ==> Checking $folder_path"
+            all_matches=""
+            i=0
+            for target_dir in "${TARGET_DIRECTORIES[@]}"
+            do
+                matches=$(find $CBIG_CODE_DIR/$target_dir -name "$folder_name" ! -samefile $CBIG_CODE_DIR/$folder_path) 
+                if [[ ${matches} ]]; then
+                    if [ $i == 1 ]; then
+                        all_matches="$matches"
+                    else
+                        all_matches="$all_matches $matches"
+                    fi
+                fi
+            done
+            if [[ ${all_matches} ]]; then
+                # check all matches
+                for match in "${all_matches[@]}"
+                do
+                    if [[ $match != */non_default_packages/* ]] && [[ $folder_path != */non_default_packages/* ]]; then
+                        classname_with_conflict=1 
+                    fi
+                    if [[ $match == */non_default_packages/* ]] || [[ $folder_path == */non_default_packages/* ]]; then
+                        class_in_nondefault=1 
+                    fi
+                    echo "!!!Find conflict: $match"
+                done
+                if [[ $classname_with_conflict == 1 ]]; then
+                    echo "[FAILED] Abort pushing."
+                    exit 1
+                fi
+                if [[ $class_in_nondefault == 1 ]]; then
+                    echo "[WARNING] The user should discuss with the admin about how to handle the conflicts."
+                    push_or_not
+                fi
+            fi
+        fi
+    done
+done
+echo "  [PASSED]"
+
+######
+# 4.  (files in stable_projects/xxx/xxx (exclude Thomas, Alex, Gia, Xiuming, Raphael))[.m, .c, .cpp, .sh, .csh, .py, .pl, .r]
+######
+EXTENSIONS_TO_CHECK=("m" "c" "cpp" "sh" "csh" "py" "pl" "r")
+EXCLUDED_DIRECTORIES=("Yeo2011_fcMRI_clustering" "Schaefer2018_LocalGlobal" "Zhang2016_ADFactors" "Liegeois2017_Surrogates")
+
+echo -e "\n==> [Check 4] Checking stable_projects/xxx/xxx"
+for project_path in $CBIG_CODE_DIR/stable_projects/*/*
+do
+    project_in_exclude_directory=0
+    echo -e "\n===> Checking $project_path"
+    all_with_valid_prefix=1
+    for exclude_directory in "${EXCLUDED_DIRECTORIES[@]}" 
+    do
+        if [[ "$project_path" == */${exclude_directory} ]]; then
+            project_in_exclude_directory=1
+            break
+        fi
+    done
+    if [[ $project_in_exclude_directory == 1 ]]; then
+        continue
+    fi
+
+    cmd="files_in_project=(\$(find $project_path -type f"
+    i=0
+    for ext in ${EXTENSIONS_TO_CHECK[@]}
+    do
+        i=$((i+1))
+        if [ $i == 1 ]; then
+            cmd="$cmd -name \"*.$ext\""
+        else
+            cmd="$cmd -or -name \"*.$ext\""
+        fi
+    done
+    cmd="$cmd))"
+    eval $cmd
+    ###
+    # find the project name based on first file
+    ###
+    first_file="${files_in_project[0]}"
+    first_filename=( $(basename "$first_file"))
+    project_name=$(echo $first_filename | awk -F '_' '{print $2}')
+
+    ###
+    # check whether function name follows CBIG_<project_name>_xxx
+    ###
+    echo -e "\n====> Check whether all function names follow CBIG_<project_name>_xxx"
+    i=0
+    for file_path in "${files_in_project[@]}"
+    do
+        i=$((i+1))
+        if [[ "$i" != "1" ]]; then
+            filename=( $(basename "$file_path"))
+            if [[ "$filename" != "CBIG_${project_name}_"* ]]; then
+                echo "!!!Find problematic file: $file_path"
+                all_with_valid_prefix=0
+            fi
+        fi
+        
+    done
+    if [[ $all_with_valid_prefix == 0 ]]; then
+        echo "[FAILED] Please make sure all scripts have filename CBIG_<project_name>_xxx"
+        exit 1
+    fi
+
+    ###
+    # check whether all projects have the config/CBIG_<project_name>_tested_config.sh
+    ###
+    echo -e "\n====> Check whether this project has config/CBIG_<project_name>_tested_config.sh"
+    all_with_config=1
+    if [[ -e $project_path/config/CBIG_${project_name}_tested_config.sh ]]; then
+        secondline=`sed -n 2p $project_path/config/CBIG_${project_name}_tested_config.sh`
+        if [[ "$secondline" != "# Last successfully run on"* ]]; then
+            all_with_config=0
+            echo "$project_path/config/CBIG_${project_name}_tested_config.sh does not have the time stamp"
+        fi
+    elif [[ -e $project_path/config/CBIG_${project_name}_tested_config.csh ]]; then
+        secondline=`sed -n 2p $project_path/config/CBIG_${project_name}_tested_config.csh`
+        if [[ "$secondline" != "# Last successfully run on"* ]]; then
+            all_with_config=0
+            echo "$project_path/config/CBIG_${project_name}_tested_config.csh does not have the time stamp"
+        fi
+    else
+        echo "$project_path does not have a CBIG_${project_name}_tested_config file"
+    fi
+    if [ $all_with_config == 0 ]; then
+        echo "    [FAILED] Stable_project $project_path does not have CBIG_${project_name}_tested_config files \
+or these files do not have time stamp."
+        echo "Please add CBIG_${project_name}_tested_config.sh or CBIG_${project_name}_tested_config.csh to \
+$project_path/config/ manually"
+        echo "Each stable project should contain a repo config file that was used when the project was last \
+tested to work."
+        echo "The second line of the config file should be a comment:"
+        echo "# Last successfully run on <spelled out date to reduce confusion, e.g., Jan 7th, 2017>"
+        exit 1
+    fi
+
+    ###
+    # if there are matlab files in a project, check whether it has config/CBIG_<project_name>_tested_startup.m
+    ###
+    m_files=$(find $project_path -name "*.m")
+    if [[ ${m_files} ]]; then
+        echo -e "\n====> Check whether this project has config/CBIG_<project_name>_tested_startup.m"
+        if [[ ! -e $project_path/config/CBIG_${project_name}_tested_startup.m ]]; then
+            echo "    [FAILED] $project_path does not have a CBIG_${project_name}_tested_startup.m file"
+            echo "Please add CBIG_${project_name}_tested_startup.m to $project_path/config/ manually"
+            exit 1
+        fi
+        echo "    [PASSED]"
+    fi
+
+    ###
+    # if there are python files in a project, check whether it has config/CBIG_<project_name>_python_env.txt
+    ###
+    py_files=$(find $project_path -name "*.py")
+    if [[ ${py_files} ]]; then
+        echo -e "\n====> Check whether this project has config/CBIG_<project_name>_python_env.txt"
+        if [[ ! -e $project_path/config/CBIG_${project_name}_python_env.txt ]]; then
+            echo "    [FAILED] $project_path does not have a CBIG_${project_name}_python_env.txt file"
+            echo "Please add CBIG_${project_name}_python_env.txt to $project_path/config/ manually"
+            exit 1
+        fi
+        echo "    [PASSED]"
+    fi
+done
+exit 0
+
+
+
