Initial release for Sun2019_ADJointFactors project
Why:

*

This change addresses the need by:

*

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -27,23 +27,27 @@ then
     fi
 fi
 
+# create log file
+logfile=$(mktemp)
+
 ######
 # 1. (committed files)[.m, .c, .cpp, .sh, .csh, .py, .pl, .r]{stable_projects, utilities, data}
 ######
 ###
 # Find the committed files that we want to check 
 ###
-files_to_be_committed=($(git diff --cached --name-status | awk '(($1 != "D") && ($1 != "U")) { print $2 }'))
-
-EXTENSIONS_TO_CHECK=("m" "c" "cpp" "sh" "csh" "py" "pl" "r")
-DIRECTORIES_TO_CHECK=("stable_projects" "utilities" "data")
-EXCLUDED_FILES=("Surf2SurfGui.m" "Vol2SurfGui.m" "CBIG_tested_config.sh" "CBIG_tested_config.csh")
+files_to_be_committed=($(git diff --cached --name-status | awk '(($1 != "D") && ($1 != "U")) {if ($1 ~ /^R/) print $3; else print $2}'))
 
 ###
 # Check whether committed files have the 'CBIG_' prefix 
 ###
+# do not check CBIG_ prefix for python scripts
+EXTENSIONS_TO_CHECK=("m" "c" "cpp" "sh" "csh" "pl" "r")
+DIRECTORIES_TO_CHECK=("stable_projects" "utilities" "data")
+EXCLUDED_FILES=("Surf2SurfGui.m" "Vol2SurfGui.m" "CBIG_tested_config.sh" "CBIG_tested_config.csh")
+
 PREFIX="CBIG_"
-echo -e "\n==> [Check] Checking that committed files have $PREFIX prefix.."
+echo -e "\n==> [Check] Checking that committed files have $PREFIX prefix.." | tee -a $logfile
 
 all_with_valid_prefixes=1
 for file_path in "${files_to_be_committed[@]}"
@@ -58,7 +62,7 @@ do
         fi
     done
     if [ $file_in_exclude == 1 ]; then
-        echo "$file_name will not be checked for $PREFIX prefix"
+        echo "$file_name will not be checked for $PREFIX prefix" | tee -a $logfile
         continue
     fi
     for directory in "${DIRECTORIES_TO_CHECK[@]}"
@@ -68,7 +72,7 @@ do
             do
                 if [[ $file_name != $PREFIX* ]] && [[ $file_name == *.$ext ]]; then
                     all_with_valid_prefixes=0
-                    echo "$file_path does not have a $PREFIX prefix, please fix it manually."
+                    echo "$file_path does not have a $PREFIX prefix, please fix it manually." | tee -a $logfile
                 fi
             done
         fi
@@ -76,17 +80,20 @@ do
 done
 
 if [ $all_with_valid_prefixes == 0 ]; then
-    echo "   [FAILED] There are functions without $PREFIX prefix. Abort committing."
-    exit 1
+    echo "   [FAILED] There are functions without $PREFIX prefix. Abort committing." | tee -a $logfile
+else
+    echo "   [PASSED]" | tee -a $logfile
 fi
-echo "   [PASSED]"
 
 ###
 # check whether committed files have the MIT license 
 ###
+# include python scripts
+EXTENSIONS_TO_CHECK=("m" "c" "cpp" "sh" "csh" "py" "pl" "r")
+
 mit_license="Written by [your name] and CBIG under MIT license: https://github.com/ThomasYeoLab/CBIG/blob/master/LICENSE.md"
 all_with_license=1
-echo -e "\n==> [Check] Checking that committed files have MIT license.."
+echo -e "\n==> [Check] Checking that committed files have MIT license.." | tee -a $logfile
 for file_path in "${files_to_be_committed[@]}"
 do
     file_in_exclude=0
@@ -99,7 +106,7 @@ do
         fi
     done
     if [ $file_in_exclude == 1 ]; then
-        echo "$file_name will not be checked for MIT license"
+        echo "$file_name will not be checked for MIT license" | tee -a $logfile
         continue
     fi
     for directory in "${DIRECTORIES_TO_CHECK[@]}"
@@ -111,14 +118,14 @@ do
                     license_line=`grep "MIT license" $file_path`
                     if [[ "$license_line" == "" ]]; then
                         all_with_license=0
-                        echo "$file_path does not have a MIT license"
+                        echo "$file_path does not have a MIT license" | tee -a $logfile
                     elif [[ "$license_line" == *"CBIG under MIT license: https://github.com/ThomasYeoLab/CBIG/blob/master/LICENSE.md" && "$license_line" == *"Written by"* ]]; then
                         # do nothing
                         :
                     else
                         all_with_license=0
-                        echo "$file_path does not follow our MIT license format: "
-                        echo "$mit_license"
+                        echo "$file_path does not follow our MIT license format: " | tee -a $logfile
+                        echo "$mit_license" | tee -a $logfile
                     fi
                 fi
             done
@@ -127,18 +134,65 @@ do
 done
 
 if [ $all_with_license == 0 ]; then
-    echo "   [FAILED] There are functions without or not following our MIT license. Abort committing."
-    echo "For matlab functions, you can use setup/check_license/CBIG_check_license_matlab_file.sh to add MIT license"
-    echo "For other languages, please add MIT license manually:"
-    echo "$mit_license"
-    exit 1
+    echo "   [FAILED] There are functions without or not following our MIT license. Abort committing." | tee -a $logfile
+    echo "For matlab functions, you can use setup/check_license/CBIG_check_license_matlab_file.sh to add MIT license" | tee -a $logfile
+    echo "For other languages, please add MIT license manually:" | tee -a $logfile
+    echo "$mit_license" | tee -a $logfile
+else
+    echo "   [PASSED]" | tee -a $logfile
 fi
-echo "   [PASSED]"
+
+###
+# check whether committed files have lines whose length is more than 120 characters 
+###
+all_within_120=1
+echo -e "\n==> [Check] Checking that committed files have lines whose length is within 120 characters .." | tee -a $logfile
+for file_path in "${files_to_be_committed[@]}"
+do
+    file_in_exclude=0
+    file_name=$(basename $file_path)
+    for excluded_file in "${EXCLUDED_FILES[@]}"
+    do
+        if [[ $file_name == $excluded_file ]]; then
+            file_in_exclude=1
+            break
+        fi
+    done
+    if [ $file_in_exclude == 1 ]; then
+        echo "$file_name will not be checked for character limit" | tee -a $logfile
+        continue
+    fi
+    for directory in "${DIRECTORIES_TO_CHECK[@]}"
+    do
+        if [[ $file_path == $directory/* ]] || [[ $file_path == $file_name ]]; then
+            for ext in "${EXTENSIONS_TO_CHECK[@]}"
+            do
+                if [[ $file_name = *.$ext ]]; then
+                    line_lengths=`awk '{print length}' $file_path`
+                    i=1
+                    for line_length in ${line_lengths}; do
+                        if [ $line_length -gt 120 ]; then
+                            echo "$file_name: Line $i: has $line_length characters > 120 characters. Shorten it." | tee -a $logfile
+                            all_within_120=0
+                        fi
+                        i=$(($i+1))
+                    done
+                fi
+            done
+        fi
+    done
+done
+
+if [ $all_within_120 == 0 ]; then
+    echo "   [FAILED] There are scripts which does not follow 120 characters limit of each line. Abort committing." | tee -a $logfile
+else
+    echo "   [PASSED]"
+fi
 
 ######
 # 2. (committed files)[.m]{stable_projects, utilities, data}
 ######
-files_to_be_committed=($(git diff --cached --name-status | awk '(($1 != "D") && ($1 != "U")) { print $2 }'))
+files_to_be_committed=($(git diff --cached --name-status | awk '(($1 != "D") && ($1 != "U")) {if ($1 ~ /^R/) print $3; else print $2}'))
 
 EXTENSIONS_TO_CHECK=("m")
 DIRECTORIES_TO_CHECK=("stable_projects" "utilities" "data")
@@ -161,7 +215,7 @@ do
         fi
     done
     if [ $file_in_exclude == 1 ]; then
-        echo "$file_name will not be checked for rmpath"
+        echo "$file_name will not be checked for rmpath" | tee -a $logfile
         continue
     fi
     for directory in "${DIRECTORIES_TO_CHECK[@]}"
@@ -180,7 +234,7 @@ do
                         rmpath_match=(`grep "$rmpath_line_backslash" $file_path`)
                         if [[ "$rmpath_match" == "" ]]; then
                             all_with_valid_rmpath=0
-                            echo "$file_path does not have a '$rmpath_line' at the end, please fix it manually."
+                            echo "$file_path does not have a '$rmpath_line' at the end, please fix it manually." | tee -a $logfile
                         fi
                     done < $tmpfile
                     rm $tmpfile
@@ -191,15 +245,15 @@ do
 done
 
 if [ $all_with_valid_rmpath == 0 ]; then
-    echo "   [FAILED] There are functions without 'rmpath' at the end. Abort committing."
-    exit 1
+    echo "   [FAILED] There are functions without 'rmpath' at the end. Abort committing." | tee -a $logfile
+else
+    echo "   [PASSED]"
 fi
-echo "   [PASSED]"
 
 ######
 # 3. (folders of committed files)[@xxx]{stable_projects, utilities, data}
 ######
-files_to_be_committed=($(git diff --cached --name-status | awk '(($1 != "D") && ($1 != "U")) { print $2 }'))
+files_to_be_committed=($(git diff --cached --name-status | awk '(($1 != "D") && ($1 != "U")) {if ($1 ~ /^R/) print $3; else print $2}'))
 
 # find the folders of comitted files
 cnt=${#files_to_be_committed[@]}
@@ -215,7 +269,7 @@ DIRECTORIES_TO_CHECK=("stable_projects" "utilities" "data")
 # check whether matlab classes have CBIG_ prefix
 ###
 PREFIX="CBIG_"
-echo -e "\n==> [Check] Checking that matlab classes have $PREFIX prefix.."
+echo -e "\n==> [Check] Checking that matlab classes have $PREFIX prefix.." | tee -a $logfile
 
 all_with_valid_prefixes=1
 for folder in "${folders_to_be_committed[@]}"
@@ -225,16 +279,81 @@ do
         if [[ $folder == $directory/* ]] && [[ $folder == *@* ]]; then
             if [[ $folder != *@${PREFIX}* ]]; then
                 all_with_valid_prefixes=0
-                echo "Matlab class $folder does not have a $PREFIX prefix, please fix it manually." 
+                echo "Matlab class $folder does not have a $PREFIX prefix, please fix it manually." | tee -a $logfile
             fi
         fi
     done
 done
 if [ $all_with_valid_prefixes == 0 ]; then
-    echo "   [FAILED] There are Matlab classes without $PREFIX prefix. Abort committing."
-    exit 1
+    echo "   [FAILED] There are Matlab classes without $PREFIX prefix. Abort committing." | tee -a $logfile
+else
+    echo "   [PASSED]" | tee -a $logfile
 fi
-echo "   [PASSED]"
+
+######
+# 4. (committed files)[.py]{stable_projects, utilities, data}
+######
+files_to_be_committed=($(git diff --cached --name-status | awk '(($1 != "D") && ($1 != "U")) {if ($1 ~ /^R/) print $3; else print $2}'))
+
+EXTENSIONS_TO_CHECK=("py")
+DIRECTORIES_TO_CHECK=("stable_projects" "utilities" "data")
+EXCLUDED_FILES=("Surf2SurfGui.m" "Vol2SurfGui.m" "CBIG_tested_config.sh" "CBIG_tested_config.csh" "tested_startup.m")
+
+all_yapf_format=1
+echo -e "\n==> [Check] Checking that committed python files follow yapf pep8 format .." | tee -a $logfile
+for file_path in "${files_to_be_committed[@]}"
+do
+    file_in_exclude=0
+    file_name=$(basename $file_path)
+    for excluded_file in "${EXCLUDED_FILES[@]}"
+    do
+        if [[ $file_name == $excluded_file ]]; then
+            file_in_exclude=1
+            break
+        fi
+    done
+    if [ $file_in_exclude == 1 ]; then
+        echo "$file_name will not be checked for pep8 format" | tee -a $logfile
+        continue
+    fi
+    for directory in "${DIRECTORIES_TO_CHECK[@]}"
+    do
+        if [[ $file_path == $directory/* ]] || [[ $file_path == $file_name ]]; then
+            for ext in "${EXTENSIONS_TO_CHECK[@]}"
+            do
+                if [[ $file_name = *.$ext ]]; then
+                    yapf_output=$(PYTHONPATH=${CBIG_CODE_DIR}/external_packages/python/yapf-master \
+                    python ${CBIG_CODE_DIR}/external_packages/python/yapf-master/yapf -d ${file_path})
+                    if [ ! -z "$yapf_output" ]; then
+                        echo "$file_path does not follow yapf pep8 format please use following command to format it." | tee -a $logfile
+                        echo "PYTHONPATH=\${CBIG_CODE_DIR}/external_packages/python/yapf-master \
+python \${CBIG_CODE_DIR}/external_packages/python/yapf-master/yapf -i ${file_path}" | tee -a $logfile
+                        all_yapf_format=0
+                    fi
+                fi
+            done
+        fi
+    done
+done
+
+if [ $all_yapf_format == 0 ]; then
+    echo "   [FAILED] There are python scripts which does not follow yapf pep8 format. Abort committing." | tee -a $logfile
+else
+    echo "   [PASSED]" | tee -a $logfile
+fi
+
+###
+# if any checks failed,exit the program
+###
+if [ $all_with_valid_prefixes == 0 -o $all_with_license == 0 -o $all_within_120 == 0 -o \
+    $all_with_valid_rmpath == 0 -o $all_with_valid_prefixes == 0 -o $all_yapf_format == 0 ]; then
+    echo "[FAILED] Some checks failed." | tee -a $logfile
+    echo "Check pre-commit hook log file: $logfile" | tee -a $logfile
+    exit 1
+else
+    echo "[PASSED]" | tee -a $logfile
+    echo "Check pre-commit hook log file: $logfile" | tee -a $logfile
+fi
 
 
 git add .
diff --git a/hooks/pre-push b/hooks/pre-push
--- a/hooks/pre-push
+++ b/hooks/pre-push
@@ -1,5 +1,8 @@
 #!/bin/sh
 
+# create log file
+logfile=$(mktemp)
+
 ###
 # Ask the user whether he wants to continue or not
 ###
@@ -29,7 +32,7 @@ EXCLUDED_FILES=("Surf2SurfGui.m" "Vol2SurfGui.m" "CBIG_tested_config.sh" "CBIG_t
 ###
 # Check whether function CBIG_xxx has been used in other functions
 ###
-echo -e "\n==> [Check 1] Checking whether function CBIG_xxx has been used in other functions"
+echo -e "\n==> [Check 1] Checking whether function CBIG_xxx has been used in other functions" | tee -a $logfile
 for file_path in "${files_to_be_checked[@]}"
 do
     file_name=( $(basename "$file_path") )
@@ -52,22 +55,22 @@ do
         for directory in "${DIRECTORIES_TO_CHECK[@]}"
         do
             if [[ $file_path == $directory/* ]] && [[ $file_name == *.$ext ]]; then
-                echo -e "\n  ==> Checking $file_path"
+                echo -e "\n  ==> Checking $file_path" | tee -a $logfile
                 $CBIG_CODE_DIR/setup/check_function_format/CBIG_check_whether_function_used_in_other_functions_wrapper.sh \
                 $file_path silent
             fi
         done
     done
 done
-echo "  [DONE]"
+echo "  [DONE]" | tee -a $logfile
 
 ###
 # comments about replacing function name
 ###
-echo -e "\n==> [Useful function] Replace old function name with new function name"
-echo "If you have renamed a function and want to change all instances of old function to the new function, you can use: "
-echo "setup/replace_old_with_new_func_name/CBIG_replace_old_with_new_function_name_wrapper.sh"
-echo ""
+echo -e "\n==> [Useful function] Replace old function name with new function name" | tee -a $logfile
+echo "If you have renamed a function and want to change all instances of old function to the new function, you can use: " | tee -a $logfile
+echo "setup/replace_old_with_new_func_name/CBIG_replace_old_with_new_function_name_wrapper.sh" | tee -a $logfile
+echo "" | tee -a $logfile
 
 ###
 # Ask the user whether he wants to continue or not
@@ -91,7 +94,7 @@ TARGET_DIRECTORIES=("utilities" "stable_projects" "data" "external_packages")
 ###
 # Check whether function name xxx has conflict with other function names
 ###
-echo -e "\n==> [Check 2] Checking whether function name xxx has conflict with other function names"
+echo -e "\n==> [Check 2] Checking whether function name xxx has conflict with other function names" | tee -a $logfile
 for file_path in "${files_to_be_checked[@]}"
 do
     file_name=( $(basename "$file_path") )
@@ -145,14 +148,13 @@ do
                         if [[ $match == */non_default_packages/* ]] || [[ $file_path == */non_default_packages/* ]]; then
                             file_in_nondefault=1 
                         fi
-                        echo "$match"
+                        echo "$match" | tee -a $logfile
                     done
                     if [[ $filename_with_conflict == 1 ]]; then
-                        echo "[FAILED] Abort pushing."
-                        exit 1
+                        echo "[FAILED] Abort pushing." | tee -a $logfile
                     fi
                     if [[ $file_in_nondefault == 1 ]]; then
-                        echo "[WARNING] The user should discuss with the admin about how to handle the conflicts."
+                        echo "[WARNING] The user should discuss with the admin about how to handle the conflicts." | tee -a $logfile
                         push_or_not
                     fi
                 fi
@@ -160,7 +162,9 @@ do
         done
     done
 done
-echo "  [PASSED]"
+if [ $filename_with_conflict == 0 -a $file_in_nondefault == 0 ]; then
+    echo "  [PASSED]" | tee -a $logfile
+fi
 
 ######
 # 3.  (folders of different files between upstream/develop and current branch)[@xxx]
@@ -184,7 +188,7 @@ unique_folders_to_be_checked=($(echo ${folders_to_be_checked[@]} | tr ' ' '\n' |
 ###
 # Check whether class name @xxx has conflict with other class names
 ###
-echo -e "\n==> [Check 3] Checking whether Matlab class name @xxx has conflict with other class names"
+echo -e "\n==> [Check 3] Checking whether Matlab class name @xxx has conflict with other class names" | tee -a $logfile
 for folder_path in "${unique_folders_to_be_checked[@]}"
 do
     folder_name=( $(basename "$folder_path") )
@@ -218,29 +222,32 @@ do
                     if [[ $match == */non_default_packages/* ]] || [[ $folder_path == */non_default_packages/* ]]; then
                         class_in_nondefault=1 
                     fi
-                    echo "!!!Find conflict: $match"
+                    echo "!!!Find conflict: $match" | tee -a $logfile
                 done
                 if [[ $classname_with_conflict == 1 ]]; then
-                    echo "[FAILED] Abort pushing."
-                    exit 1
+                    echo "[FAILED] Abort pushing." | tee -a $logfile
                 fi
                 if [[ $class_in_nondefault == 1 ]]; then
-                    echo "[WARNING] The user should discuss with the admin about how to handle the conflicts."
+                    echo "[WARNING] The user should discuss with the admin about how to handle the conflicts." | tee -a $logfile
                     push_or_not
                 fi
             fi
         fi
     done
 done
-echo "  [PASSED]"
+if [ $classname_with_conflict == 0 -a $class_in_nondefault == 0 ]; then
+    echo "  [PASSED]" | tee -a $logfile
+fi
 
 ######
 # 4.  (files in stable_projects/xxx/xxx (exclude Thomas, Alex, Gia, Xiuming, Raphael))[.m, .c, .cpp, .sh, .csh, .py, .pl, .r]
 ######
-EXTENSIONS_TO_CHECK=("m" "c" "cpp" "sh" "csh" "py" "pl" "r")
+exit_flag=0
+EXTENSIONS_TO_CHECK=("m" "c" "cpp" "sh" "csh" "pl" "r")
 EXCLUDED_DIRECTORIES=("Zhang2016_ADFactors")
+STANDALONE_EX_DIR=("Zhang2016_ADFactors" "Liegeois2017_Surrogates" "Wu2017_RegistrationFusion")
 
-echo -e "\n==> [Check 4] Checking stable_projects/xxx/xxx"
+echo -e "\n==> [Check 4] Checking stable_projects/xxx/xxx" | tee -a $logfile
 for project_path in $CBIG_CODE_DIR/stable_projects/*/*
 do
     project_in_exclude_directory=0
@@ -280,7 +287,7 @@ do
     ###
     # check whether function name follows CBIG_<project_name>_xxx
     ###
-    echo -e "\n====> Check whether all function names follow CBIG_<project_name>_xxx"
+    echo -e "\n====> Check whether all function names follow CBIG_<project_name>_xxx" | tee -a $logfile
     i=0
     for file_path in "${files_in_project[@]}"
     do
@@ -288,47 +295,51 @@ do
         if [[ "$i" != "1" ]]; then
             filename=( $(basename "$file_path"))
             if [[ "$filename" != "CBIG_${project_name}_"* ]]; then
-                echo "!!!Find problematic file: $file_path"
+                echo "!!!Find problematic file: $file_path" | tee -a $logfile
                 all_with_valid_prefix=0
             fi
         fi
         
     done
     if [[ $all_with_valid_prefix == 0 ]]; then
-        echo "[FAILED] Please make sure all scripts have filename CBIG_<project_name>_xxx"
-        exit 1
+        exit_flag=1
+        echo "[FAILED] Please make sure all scripts have filename CBIG_<project_name>_xxx" | tee -a $logfile
+    else
+        echo "    [PASSED]" | tee -a $logfile
     fi
 
     ###
     # check whether all projects have the config/CBIG_<project_name>_tested_config.sh
     ###
-    echo -e "\n====> Check whether this project has config/CBIG_<project_name>_tested_config.sh"
+    echo -e "\n====> Check whether this project has config/CBIG_<project_name>_tested_config.sh" | tee -a $logfile
     all_with_config=1
     if [[ -e $project_path/config/CBIG_${project_name}_tested_config.sh ]]; then
         secondline=`sed -n 2p $project_path/config/CBIG_${project_name}_tested_config.sh`
         if [[ "$secondline" != "# Last successfully run on"* ]]; then
             all_with_config=0
-            echo "$project_path/config/CBIG_${project_name}_tested_config.sh does not have the time stamp"
+            echo "$project_path/config/CBIG_${project_name}_tested_config.sh does not have the time stamp" | tee -a $logfile
         fi
     elif [[ -e $project_path/config/CBIG_${project_name}_tested_config.csh ]]; then
         secondline=`sed -n 2p $project_path/config/CBIG_${project_name}_tested_config.csh`
         if [[ "$secondline" != "# Last successfully run on"* ]]; then
             all_with_config=0
-            echo "$project_path/config/CBIG_${project_name}_tested_config.csh does not have the time stamp"
+            echo "$project_path/config/CBIG_${project_name}_tested_config.csh does not have the time stamp" | tee -a $logfile
         fi
     else
-        echo "$project_path does not have a CBIG_${project_name}_tested_config file"
+        echo "$project_path does not have a CBIG_${project_name}_tested_config file" | tee -a $logfile
     fi
     if [ $all_with_config == 0 ]; then
+        exit_flag=1
         echo "    [FAILED] Stable_project $project_path does not have CBIG_${project_name}_tested_config files \
-or these files do not have time stamp."
+or these files do not have time stamp." | tee -a $logfile
         echo "Please add CBIG_${project_name}_tested_config.sh or CBIG_${project_name}_tested_config.csh to \
-$project_path/config/ manually"
+$project_path/config/ manually" | tee -a $logfile
         echo "Each stable project should contain a repo config file that was used when the project was last \
-tested to work."
-        echo "The second line of the config file should be a comment:"
-        echo "# Last successfully run on <spelled out date to reduce confusion, e.g., Jan 7th, 2017>"
-        exit 1
+tested to work." | tee -a $logfile
+        echo "The second line of the config file should be a comment:" | tee -a $logfile
+        echo "# Last successfully run on <spelled out date to reduce confusion, e.g., Jan 7th, 2017>" | tee -a $logfile
+    else
+        echo "    [PASSED]" | tee -a $logfile
     fi
 
     ###
@@ -336,13 +347,14 @@ tested to work."
     ###
     m_files=$(find $project_path -name "*.m")
     if [[ ${m_files} ]]; then
-        echo -e "\n====> Check whether this project has config/CBIG_<project_name>_tested_startup.m"
+        echo -e "\n====> Check whether this project has config/CBIG_<project_name>_tested_startup.m" | tee -a $logfile
         if [[ ! -e $project_path/config/CBIG_${project_name}_tested_startup.m ]]; then
-            echo "    [FAILED] $project_path does not have a CBIG_${project_name}_tested_startup.m file"
-            echo "Please add CBIG_${project_name}_tested_startup.m to $project_path/config/ manually"
-            exit 1
+            exit_flag=1
+            echo "    [FAILED] $project_path does not have a CBIG_${project_name}_tested_startup.m file" | tee -a $logfile
+            echo "Please add CBIG_${project_name}_tested_startup.m to $project_path/config/ manually" | tee -a $logfile
+        else
+            echo "    [PASSED]" | tee -a $logfile
         fi
-        echo "    [PASSED]"
     fi
 
     ###
@@ -350,27 +362,87 @@ tested to work."
     ###
     py_files=$(find $project_path -name "*.py")
     if [[ ${py_files} ]]; then
-        echo -e "\n====> Check whether this project has config/CBIG_<project_name>_python_env.txt"
-        if [[ ! -e $project_path/config/CBIG_${project_name}_python_env.txt ]]; then
-            echo "    [FAILED] $project_path does not have a CBIG_${project_name}_python_env.txt file"
-            echo "Please add CBIG_${project_name}_python_env.txt to $project_path/config/ manually"
-            exit 1
+        echo -e "\n====> Check whether this project has config/CBIG_<project_name>_python_env.yml" | tee -a $logfile
+        count=`ls -1 $project_path/config/*.yml 2>/dev/null | wc -l`
+        if [[ $count == 0 ]]; then
+            exit_flag=1
+            echo "    [FAILED] $project_path does not have a CBIG_\${project_name}_python_env.yml file" | tee -a $logfile
+            echo "Please add CBIG_${project_name}_python_env.yml to $project_path/config/ manually" | tee -a $logfile
+        else
+            echo "    [PASSED]" | tee -a $logfile
         fi
-        echo "    [PASSED]"
+        # check keras.json
+        yml_file=$(ls -1 $project_path/config/*.yml)
+        keras_line=$(grep keras $yml_file)
+        if [[ ! -z "$keras_line" ]]; then
+            echo -e "\n====> Check whether this project has config/keras.json" | tee -a $logfile
+            if [[ ! -e $project_path/config/keras.json ]]; then
+                exit_flag=1
+                echo "    [FAILED] $project_path does not have keras.json file" | tee -a $logfile
+                echo "Please add keras.json to $project_path/config/ manually" | tee -a $logfile
+            else
+                echo "    [PASSED]" | tee -a $logfile
+            fi
+        fi
+    fi
+
+    ###
+    # check whether the project has config/CBIG_<project_name>_generate_standalone.sh
+    ###
+    project_in_standalone_ex_dir=0
+    for exclude_directory in "${STANDALONE_EX_DIR[@]}" 
+    do
+        if [[ "$project_path" == */${exclude_directory} ]]; then
+            project_in_standalone_ex_dir=1
+            break
+        fi
+    done
+    if [[ $project_in_standalone_ex_dir == 0 ]]; then
+        echo -e "\n====> Check whether this project has config/CBIG_<project_name>_generate_standalone.sh" | tee -a $logfile
+        if [[ ! -e $project_path/config/CBIG_${project_name}_generate_standalone.sh ]]; then
+            exit_flag=1
+            echo "    [FAILED] $project_path does not have a CBIG_${project_name}_generate_standalone.sh" | tee -a $logfile
+            echo "Please add CBIG_${project_name}_generate_standalone.sh to $project_path/config/ manually" | tee -a $logfile
+        else
+            echo "    [PASSED]" | tee -a $logfile
+        fi
     fi
 
     ###
     # check whether all projects have the unit_tests folder
     ###
-    echo -e "\n====> Check whether this project has unit_tests folder"
+    echo -e "\n====> Check whether this project has unit_tests folder" | tee -a $logfile
     if [ ! -d "$project_path/unit_tests" ]; then
-        echo "    [FAILED] $project_path does not have a unit_tests folder"
-        echo "Please add a unit_tests folder under $project_path manually"
-        exit 1
+        exit_flag=1
+        echo "    [FAILED] $project_path does not have a unit_tests folder" | tee -a $logfile
+        echo "Please add a unit_tests folder under $project_path manually" | tee -a $logfile
+    else
+        echo "    [PASSED]" | tee -a $logfile
     fi
-    echo "    [PASSED]"
- 
+
+    ###
+    # check whether all projects have the examples folder
+    ###
+    echo -e "\n====> Check whether this project has examples folder" | tee -a $logfile
+    if [ ! -d "$project_path/examples" ]; then
+        exit_flag=1
+        echo "    [FAILED] $project_path does not have a examples folder" | tee -a $logfile
+        echo "Please add a examples folder under $project_path manually" | tee -a $logfile
+    else
+        echo "    [PASSED]" | tee -a $logfile
+    fi
 done
+
+if [ $exit_flag == 1 ]; then
+    echo "[FAILED] Some checks failed." | tee -a $logfile
+    echo "Check pre-push hook log file: $logfile" | tee -a $logfile
+    exit 1
+else
+    echo "[PASSED]" | tee -a $logfile
+    echo "Check pre-commit hook log file: $logfile" | tee -a $logfile
+fi
+
+
 exit 0
 
 
