v0.29.4-Fix_indentation
Why:

Replace tabs with spaces

This change addresses the need by:

All

diff --git a/setup/CBIG_pbsubmit b/setup/CBIG_pbsubmit
--- a/setup/CBIG_pbsubmit
+++ b/setup/CBIG_pbsubmit
@@ -8,9 +8,9 @@ set n = `echo $argv | grep -e -help | wc -l`
 
 # if there is no arguments or there is -help option 
 if( $#argv == 0 || $n != 0 ) then
-	# print help	
-	cat $0 | awk 'BEGIN{prt=0}{if(prt) print $0; if($1 == "BEGINHELP") prt = 1 }'
-	exit 0;
+    # print help
+    cat $0 | awk 'BEGIN{prt=0}{if(prt) print $0; if($1 == "BEGINHELP") prt = 1 }'
+    exit 0;
 endif
 
 ######################################################
@@ -21,7 +21,7 @@ set username = `whoami`
 set work_dir = /home/$username/cluster/ 
 
 if (! -e $work_dir) then
-        mkdir -p $work_dir
+    mkdir -p $work_dir
 endif
 
 ################################
@@ -76,17 +76,17 @@ endif
 # check current node. Job can only be submitted from the headnode
 set currnode = `hostname`
 if ( "$currnode" != "headnode" ) then
-	if ( "$ngpus" != "" ) then
-		echo "ERROR: You are requesting GPUs but not submitting jobs from the headnode. Please submit jobs from the headnode."
-		exit 1
-	endif
-	echo "WARNING: ssh from $currnode to headnode ..."
-	# submit job
-	ssh headnode "cd $work_dir; qsub ${cmd} -- ${cmd_script}"
+    if ( "$ngpus" != "" ) then
+        echo "ERROR: You are requesting GPUs but not submitting jobs from the headnode. Please submit jobs from the headnode."
+        exit 1
+    endif
+    echo "WARNING: ssh from $currnode to headnode ..."
+    # submit job
+    ssh headnode "cd $work_dir; qsub ${cmd} -- ${cmd_script}"
 else
-	# submit job
-	cd ${work_dir}
-	echo "${cmd_script}" | qsub $cmd
+    # submit job
+    cd ${work_dir}
+    echo "${cmd_script}" | qsub $cmd
 endif
 
 sleep ${sleeptime}
@@ -95,65 +95,65 @@ exit 0
 
 ##########################################
 # Parse Arguments 
-##########################################	
+##########################################
 
 parse_args:
 set cmdline = "$argv";
 while( $#argv != 0 )
-	set flag = $argv[1]; shift;
-	
-	switch($flag)
-		case "-cmd":
-			if ( $#argv == 0 ) goto arg1err;
-			set cmd_script = ($argv[1]); shift;
-			breaksw	
+    set flag = $argv[1]; shift;
 
-		case "-walltime":
-			if ( $#argv == 0 ) goto arg1err;
-			set walltime = $argv[1]; shift;
-			breaksw	
-		
-		case "-ncpus":
-			if ( $#argv == 0 ) goto arg1err;
-			set ncpus = $argv[1]; shift;
-			breaksw	
+    switch($flag)
+        case "-cmd":
+            if ( $#argv == 0 ) goto arg1err;
+            set cmd_script = ($argv[1]); shift;
+            breaksw
 
-		case "-ngpus":
-			if ( $#argv == 0 ) goto arg1err;
-			set ngpus = $argv[1]; shift;
-			breaksw	
-		
-		case "-mem":
-			if ( $#argv == 0 ) goto arg1err;
-			set memory = $argv[1]; shift;
-			breaksw	
-			
-		case "-name":
-			if ( $#argv == 0 ) goto arg1err;
-			set jobname = $argv[1]; shift;
-			breaksw	
+        case "-walltime":
+            if ( $#argv == 0 ) goto arg1err;
+            set walltime = $argv[1]; shift;
+            breaksw
+    
+        case "-ncpus":
+            if ( $#argv == 0 ) goto arg1err;
+            set ncpus = $argv[1]; shift;
+            breaksw
 
-		case "-joberr":
-			if ( $#argv == 0 ) goto arg1err;
-			set stderr_file = $argv[1]; shift;
-			breaksw	
+        case "-ngpus":
+            if ( $#argv == 0 ) goto arg1err;
+            set ngpus = $argv[1]; shift;
+            breaksw
+    
+        case "-mem":
+            if ( $#argv == 0 ) goto arg1err;
+            set memory = $argv[1]; shift;
+            breaksw
+        
+        case "-name":
+            if ( $#argv == 0 ) goto arg1err;
+            set jobname = $argv[1]; shift;
+            breaksw
 
-		case "-jobout":
-			if ( $#argv == 0 ) goto arg1err;
-			set stdout_file = $argv[1]; shift;
-			breaksw	
+        case "-joberr":
+            if ( $#argv == 0 ) goto arg1err;
+            set stderr_file = $argv[1]; shift;
+            breaksw
 
-		case "-script":
-			if ( $#argv == 0 ) goto arg1err;
-			set script_file = $argv[1]; shift;
-			breaksw	
-			
-		default:
-			echo ERROR: Flag $flag unrecognized.
-			echo $cmdline
-			exit 1
-			breaksw
-	endsw
+        case "-jobout":
+            if ( $#argv == 0 ) goto arg1err;
+            set stdout_file = $argv[1]; shift;
+            breaksw
+
+        case "-script":
+            if ( $#argv == 0 ) goto arg1err;
+            set script_file = $argv[1]; shift;
+            breaksw
+        
+        default:
+            echo ERROR: Flag $flag unrecognized.
+            echo $cmdline
+            exit 1
+            breaksw
+    endsw
 end
 goto parse_args_return;
 
@@ -164,8 +164,8 @@ goto parse_args_return;
 
 check_params:
 if ( "$cmd_script" == "" ) then
-	echo "ERROR: submitted command or script not specified"
-	exit 1;
+    echo "ERROR: submitted command or script not specified"
+    exit 1;
 endif
 
 goto check_params_return;
@@ -173,15 +173,15 @@ goto check_params_return;
 
 ##########################################
 # ERROR message
-##########################################	
+##########################################
 
 arg1err:
-  echo "ERROR: flag $flag requires one argument"
-  exit 1
+    echo "ERROR: flag $flag requires one argument"
+    exit 1
 
 arg2err:
-  echo "ERROR: flag $flag requires two arguments"
-  exit 1
+    echo "ERROR: flag $flag requires two arguments"
+    exit 1
 
 ##############################################
 # Everything below is printed as part of help
@@ -213,16 +213,16 @@ DESCRIPTION:
     Number of CPUs = 1
     Memory = 8G
     Job output log = $HOME/cluster/STDIN.o????
-    Job error log = $HOME/cluster/STDIN.e????	 
-	
+    Job error log = $HOME/cluster/STDIN.e????
+
 REQUIRED ARGUMENTS:
     -cmd    <cmd>:  The script to be submitted.
                     IMPORTANT NOTE: If <cmd> contains string, please use double quote to quote it. e.g.,
                     -cmd "/path/my_job_script.sh input1 input2 input3"
                     or
                     my_cmd="/path/my_job_script.sh input1 input2 input3"
-                    -cmd "${my_cmd}"	
-	                             
+                    -cmd "${my_cmd}"
+                                 
 OPTIONAL ARGUMENTS:
     -walltime   <walltime>:         Specify the maximum run time (hours, minutes and seconds): HH:MM:SS. Default is 01:00:00.
     -ncpus      <ncpus>:            Specify the number of CPUs for a job. Default is 1.
@@ -233,14 +233,14 @@ OPTIONAL ARGUMENTS:
     -mem        <memory>:           Specify the amount of maximum memory required (e.g. 3G). Default is 8G.
     -name       <jobname>:          The job name.         
     -joberr     <joberr_file>:      The path to the job error log file. e.g., "/path/myjoberr.log". Default is $HOME/cluster/STDIN.e????. 
-    -jobout     <jobout_file>:      The path to the job output log file. e.g., "/path/myjobout.log". Default is $HOME/cluster/STDIN.o????.	
+    -jobout     <jobout_file>:      The path to the job output log file. e.g., "/path/myjobout.log". Default is $HOME/cluster/STDIN.o????.
     -help       : help
 
 
 EXAMPLE:
     ssh headnode
     cmd="/path/my_job_script.sh input1 input2 input3"
-	
+
     $CBIG_CODE_DIR/setup/CBIG_pbsubmit -cmd "$cmd" 
     $CBIG_CODE_DIR/setup/CBIG_pbsubmit -cmd "$cmd" -walltime 00:30:00 -mem 4G -ncpus 2
     $CBIG_CODE_DIR/setup/CBIG_pbsubmit -cmd "$cmd" -walltime 00:30:00 -mem 4G -ncpus 4 -ngpus 1
diff --git a/stable_projects/preprocessing/CBIG2022_DiffProc/TBSS/fsl_sub_torque b/stable_projects/preprocessing/CBIG2022_DiffProc/TBSS/fsl_sub_torque
--- a/stable_projects/preprocessing/CBIG2022_DiffProc/TBSS/fsl_sub_torque
+++ b/stable_projects/preprocessing/CBIG2022_DiffProc/TBSS/fsl_sub_torque
@@ -145,7 +145,7 @@ command=`basename $0`
 
 usage ()
 {
-  cat <<EOF
+cat <<EOF
 
 $command V1.1 - wrapper for job control system such as SGE
 
@@ -155,58 +155,58 @@ $command gzip *.img *.hdr
 $command -q short.q gzip *.img *.hdr
 $command -a darwin regscript rawdata outputdir ...
 
-  -T <minutes>          Estimated job length in minutes, used to auto-set queue name
-  -q <queuename>        Possible values for <queuename> are "verylong.q", "long.q" 
-                        and "short.q". See below for details
-                        Default is "long.q".
-  -a <arch-name>        Architecture [e.g., darwin or lx24-amd64]
-  -p <job-priority>     Lower priority [0:-1024] default = 0                 
-  -M <email-address>    Who to email, default = `whoami`@fmrib.ox.ac.uk 
-  -j <jid>              Place a hold on this task until job jid has completed
-  -t <filename>         Specify a task file of commands to execute in parallel
-  -N <jobname>          Specify jobname as it will appear on queue
-  -R <RAM>              Max total RAM to use for job (integer in MB)
-  -l <logdirname>       Where to output logfiles
-  -m <mailoptions>      Change the SGE mail options, see qsub for details
-  -z <output>           If <output> image or file already exists, do nothing and exit
-  -F                    Use flags embedded in scripts to set SGE queuing options
-  -s <pename>,<threads> Submit a multi-threaded task - requires a PE (<pename>) to be
-                        configured for the requested queues.
-                        <threads> specifies the number of threads to run
-  -v                    Verbose mode.
+    -T <minutes>          Estimated job length in minutes, used to auto-set queue name
+    -q <queuename>        Possible values for <queuename> are "verylong.q", "long.q" 
+                          and "short.q". See below for details
+                          Default is "long.q".
+    -a <arch-name>        Architecture [e.g., darwin or lx24-amd64]
+    -p <job-priority>     Lower priority [0:-1024] default = 0                 
+    -M <email-address>    Who to email, default = `whoami`@fmrib.ox.ac.uk 
+    -j <jid>              Place a hold on this task until job jid has completed
+    -t <filename>         Specify a task file of commands to execute in parallel
+    -N <jobname>          Specify jobname as it will appear on queue
+    -R <RAM>              Max total RAM to use for job (integer in MB)
+    -l <logdirname>       Where to output logfiles
+    -m <mailoptions>      Change the SGE mail options, see qsub for details
+    -z <output>           If <output> image or file already exists, do nothing and exit
+    -F                    Use flags embedded in scripts to set SGE queuing options
+    -s <pename>,<threads> Submit a multi-threaded task - requires a PE (<pename>) to be
+                          configured for the requested queues.
+                          <threads> specifies the number of threads to run
+    -v                    Verbose mode.
 
 Queues:
 
 There are several batch queues configured on the cluster, each with defined CPU
 time limits. All queues, except bigmem.q, have a 8GB memory limit.
 
-veryshort.q:This queue is for jobs which last under 30mins.
-short.q:    This queue is for jobs which last up to 4h. 
-long.q:     This queue is for jobs which last less than 24h. Jobs run with a
-            nice value of 10.
-verylong.q: This queue is for jobs which will take longer than 24h CPU time.
-            There is one slot per node, and jobs on this queue have a nice value
-            of 15.
-bigmem.q:   This queue is like the verylong.q but has no memory limits.
+veryshort.q: This queue is for jobs which last under 30mins.
+short.q:     This queue is for jobs which last up to 4h. 
+long.q:      This queue is for jobs which last less than 24h. Jobs run with a
+             nice value of 10.
+verylong.q:  This queue is for jobs which will take longer than 24h CPU time.
+             There is one slot per node, and jobs on this queue have a nice value
+             of 15.
+bigmem.q:    This queue is like the verylong.q but has no memory limits.
 
 EOF
 
-  exit 1
+    exit 1
 }
 
 nargs=$#
 if [ $nargs -eq 0 ] ; then
-  usage
+    usage
 fi
 
 set -- `getopt T:q:a:p:M:j:t:z:N:R:Fvm:l:s: $*`
 result=$?
 if [ $result != 0 ] ; then
-  echo "What? Your arguments make no sense!"
+    echo "What? Your arguments make no sense!"
 fi
 
 if [ $nargs -eq 0 ] || [ $result != 0 ] ; then
-  usage
+    usage
 fi
 
 POSIXLY_CORRECT=${OLD_POSIXLY_CORRECT}
@@ -268,105 +268,105 @@ fi
 scriptmode=0
 
 while [ $1 != -- ] ; do
-  case $1 in
-    -z)
-      if [ -e $2 -o `${FSLDIR}/bin/imtest $2` = 1 ] ; then
-        exit 0
-      fi
-      shift;;
-    -T)
-      map_qname $2
-      walltime=$(($2*60)) # add walltime for torque
-      shift;;
-    -q)
-      queue=$2
-      queueCmd=" -q $queue " 
-      $QCONF -sq $queue >/dev/null 2>&1
-      if [ $? -eq 1 ]; then
-          echo "Invalid queue specified!"
-          exit 127
-      fi
-      shift;;
-    -a)
-      acceptable_arch=no
-      available_archs=`qhost | tail -n +4 | awk '{print $2}' | sort | uniq`
-      for a in $available_archs; do
-    if [ $2 = $a ] ; then
-      acceptable_arch=yes
-    fi
-      done
-      if [ $acceptable_arch = yes ]; then
-          sge_arch="-l arch=$2"
-      else
-          echo "Sorry arch of $2 is not supported on this SGE configuration!"
-          echo "Should be one of:" $available_archs
-          exit 127
-      fi
-      shift;;
-    -p)
-      sge_priority="-p $2"
-      shift;;
-    -M)
-      mailto=$2
-      shift;;
-    -j)
-      jid=$2
-      sge_hold="-hold_jid $jid"
-      shift;;
-    -t)
-      taskfile=$2
-      if [ -f "$taskfile" ] ; then
-          tasks=`wc -l $taskfile | awk '{print $1}'`
-          if [ $tasks -ne 0 ]; then
-              sge_tasks="-t 1-$tasks"
-          else
-            echo "Task file ${taskfile} is empty"
-            echo "Should be a text file listing all the commands to run!"
-            exit -1
+    case $1 in
+        -z)
+          if [ -e $2 -o `${FSLDIR}/bin/imtest $2` = 1 ] ; then
+              exit 0
           fi
-      else
-          echo "Task file (${taskfile}) does not exist"
-          exit -1
-      fi
-      shift;;
-    -N)
-      JobName=$2;
-      shift;;
-    -R)
-      RAM="-l mem_free=${2}M"
-      if [[ $METHOD = "TORQUE" ]] ; then # modified mem options
-          RAM="${2}GB"
-      fi 
-      shift;;
-    -m)
-      MailOpts=$2;
-      shift;;
-    -l)
-      LogOpts="-o $2 -e $2";
-      LogDir="${2}/";
-      if [ ! -e ${2} ]; then 
-          mkdir -p $2
-      else
-      echo ${2} | grep '/dev/null' >/dev/null 2>&1
-      if [ $? -eq 1 ] && [ -f ${2} ]; then
-          echo "Log destination is a file (should be a folder)"
-          exit -1
-      fi
-      fi
-      shift;;
-    -F)
-      scriptmode=1;
-      ;;
-    -v)
-      verbose=1
-      ;;
-    -s)
-      pe_string=$2;
-      peName=`echo $pe_string | cut -d',' -f 1`
-      peThreads=`echo $pe_string | cut -d',' -f 2`
-      shift;;
-  esac
-  shift  # next flag
+          shift;;
+        -T)
+          map_qname $2
+          walltime=$(($2*60)) # add walltime for torque
+          shift;;
+        -q)
+          queue=$2
+          queueCmd=" -q $queue " 
+          $QCONF -sq $queue >/dev/null 2>&1
+          if [ $? -eq 1 ]; then
+              echo "Invalid queue specified!"
+              exit 127
+          fi
+          shift;;
+        -a)
+          acceptable_arch=no
+          available_archs=`qhost | tail -n +4 | awk '{print $2}' | sort | uniq`
+          for a in $available_archs; do
+              if [ $2 = $a ] ; then
+                  acceptable_arch=yes
+              fi
+          done
+          if [ $acceptable_arch = yes ]; then
+              sge_arch="-l arch=$2"
+          else
+              echo "Sorry arch of $2 is not supported on this SGE configuration!"
+              echo "Should be one of:" $available_archs
+              exit 127
+          fi
+          shift;;
+        -p)
+          sge_priority="-p $2"
+          shift;;
+        -M)
+          mailto=$2
+          shift;;
+        -j)
+          jid=$2
+          sge_hold="-hold_jid $jid"
+          shift;;
+        -t)
+          taskfile=$2
+          if [ -f "$taskfile" ] ; then
+               tasks=`wc -l $taskfile | awk '{print $1}'`
+               if [ $tasks -ne 0 ]; then
+                   sge_tasks="-t 1-$tasks"
+               else
+                   echo "Task file ${taskfile} is empty"
+                   echo "Should be a text file listing all the commands to run!"
+                   exit -1
+               fi
+          else
+               echo "Task file (${taskfile}) does not exist"
+               exit -1
+          fi
+          shift;;
+        -N)
+          JobName=$2;
+          shift;;
+        -R)
+          RAM="-l mem_free=${2}M"
+          if [[ $METHOD = "TORQUE" ]] ; then # modified mem options
+              RAM="${2}GB"
+          fi 
+          shift;;
+        -m)
+          MailOpts=$2;
+          shift;;
+        -l)
+          LogOpts="-o $2 -e $2";
+          LogDir="${2}/";
+          if [ ! -e ${2} ]; then 
+              mkdir -p $2
+          else
+              echo ${2} | grep '/dev/null' >/dev/null 2>&1
+              if [ $? -eq 1 ] && [ -f ${2} ]; then
+                  echo "Log destination is a file (should be a folder)"
+                  exit -1
+              fi
+          fi
+          shift;;
+        -F)
+          scriptmode=1;
+          ;;
+        -v)
+          verbose=1
+          ;;
+        -s)
+          pe_string=$2;
+          peName=`echo $pe_string | cut -d',' -f 1`
+          peThreads=`echo $pe_string | cut -d',' -f 2`
+          shift;;
+    esac
+    shift  # next flag
 done
 shift
 
@@ -424,57 +424,57 @@ case $METHOD in
        ###########################################################################
        # Test Parallel environment options
        ###########################################################################
-    if [ "x$peName" != x ]; then
-            # Is this a configured PE?
+       if [ "x$peName" != x ]; then
+           # Is this a configured PE?
 
-        $QCONF -sp $peName >/dev/null 2>&1
+           $QCONF -sp $peName >/dev/null 2>&1
 
-        if [ $? -eq 1 ]; then
-            echo $@
-            echo "$peName is not a valid PE"
-            exit -1
+           if [ $? -eq 1 ]; then
+               echo $@
+               echo "$peName is not a valid PE"
+               exit -1
+           fi
+
+           # Get a list of queues configured for this PE and confirm that the queue
+           # we have submitted to has that PE set up.
+           qstat -g c -pe $peName >/dev/null 2>&1
+           if [ $? -eq 1 ]; then
+               echo "No parallel environments configured!"
+               exit -1
+           fi
+
+           qstat -g c -pe $peName | sed '1,2d' | awk '{ print $1 }' | grep ^$queue >/dev/null 2>&1
+
+           if [ $? -eq 1 ]; then
+               echo $@
+               echo "PE $peName is not configured on $queue"
+               exit -1
+           fi
+
+           # The -w e option will result in the job failing if there are insufficient slots
+           # on any of the cluster nodes
+           pe_options="-pe $peName $peThreads -w e"
+
         fi
 
-            # Get a list of queues configured for this PE and confirm that the queue
-            # we have submitted to has that PE set up.
-        qstat -g c -pe $peName >/dev/null 2>&1
-        if [ $? -eq 1 ]; then
-            echo "No parallel environments configured!"
-            exit -1
-        fi
-
-        qstat -g c -pe $peName | sed '1,2d' | awk '{ print $1 }' | grep ^$queue >/dev/null 2>&1
-
-        if [ $? -eq 1 ]; then
-            echo $@
-            echo "PE $peName is not configured on $queue"
-            exit -1
-        fi
-
-        # The -w e option will result in the job failing if there are insufficient slots
-            # on any of the cluster nodes
-        pe_options="-pe $peName $peThreads -w e"
-
-    fi
-
-    if [ "x$tasks" = "x" ] ; then
-        if [ $scriptmode -ne 1 ] ; then
-            sge_command="qsub -V -cwd -shell n -b y -r y $queueCmd $pe_options -M $mailto -N $JobName -m $MailOpts $LogOpts $sge_arch $RAM $sge_hold"
+        if [ "x$tasks" = "x" ] ; then
+            if [ $scriptmode -ne 1 ] ; then
+                sge_command="qsub -V -cwd -shell n -b y -r y $queueCmd $pe_options -M $mailto -N $JobName -m $MailOpts $LogOpts $sge_arch $RAM $sge_hold"
+            else
+                sge_command="qsub $LogOpts $sge_arch $sge_hold"
+            fi
+            if [ $verbose -eq 1 ] ; then 
+                echo sge_command: $sge_command >&2
+                echo executing: $@ >&2
+            fi
+            exec $sge_command $@ | awk '{print $3}'
         else
-            sge_command="qsub $LogOpts $sge_arch $sge_hold"
-        fi
-        if [ $verbose -eq 1 ] ; then 
-            echo sge_command: $sge_command >&2
-            echo executing: $@ >&2
-        fi
-        exec $sge_command $@ | awk '{print $3}'
-    else
-        sge_command="qsub -V -cwd $queueCmd $pe_options -M $mailto -N $JobName -m $MailOpts $LogOpts $sge_arch $RAM $sge_hold $sge_tasks"
-        if [ $verbose -eq 1 ] ; then 
-            echo sge_command: $sge_command >&2
-            echo control file: $taskfile >&2
-        fi
-        exec $sge_command <<EOF | awk '{print $3}' | awk -F. '{print $1}'
+            sge_command="qsub -V -cwd $queueCmd $pe_options -M $mailto -N $JobName -m $MailOpts $LogOpts $sge_arch $RAM $sge_hold $sge_tasks"
+            if [ $verbose -eq 1 ] ; then 
+                echo sge_command: $sge_command >&2
+                echo control file: $taskfile >&2
+            fi
+            exec $sge_command <<EOF | awk '{print $3}' | awk -F. '{print $1}'
 #!/bin/sh
 
 #$ -S /bin/sh
@@ -491,31 +491,31 @@ EOF
 # Schedule on TORQUE cluster
 ###########################################################################
     TORQUE)
-    echo "TORQUE processing:"
-        if [ $verbose -eq 1 ] ; then 
-                echo "Running commands in: $taskfile" >&2
-            fi
+          echo "TORQUE processing:"
+          if [ $verbose -eq 1 ] ; then 
+              echo "Running commands in: $taskfile" >&2
+          fi
 
-            n=1
-        while [ $n -le $tasks ] ; do
-            # get command from taskfile
-            line=`sed -n -e ''${n}'p' $taskfile`
-            if [ $verbose -eq 1 ] ; then 
-                echo executing: $line >&2
-            fi
+          n=1
+          while [ $n -le $tasks ] ; do
+              # get command from taskfile
+              line=`sed -n -e ''${n}'p' $taskfile`
+              if [ $verbose -eq 1 ] ; then 
+                  echo executing: $line >&2
+              fi
 
-            #run command
-            logdir= $( pwd )
-            $CBIG_CODE_DIR/setup/CBIG_pbsubmit -cmd "$cmd" -walltime "$walltime" -name "$JobName" \
-                -mem "$RAM" -joberr "$logdir" -jobout "$logdir"
+              #run command
+              logdir= $( pwd )
+              $CBIG_CODE_DIR/setup/CBIG_pbsubmit -cmd "$cmd" -walltime "$walltime" -name "$JobName" \
+                  -mem "$RAM" -joberr "$logdir" -jobout "$logdir"
 
-            # pause and go on to next job 
-            sleep 2
-            n=`expr $n + 1`
-        done
+              # pause and go on to next job 
+              sleep 2
+              n=`expr $n + 1`
+          done
 
-    exit 1
-    ;;
+          exit 1
+          ;;
 
 
 ###########################################################################
@@ -524,38 +524,38 @@ EOF
 ###########################################################################
 
     NONE)
-    if [ "x$tasks" = "x" ] ; then
-        if [ $verbose -eq 1 ] ; then 
-            echo executing: $@ >&2
-        fi
+        if [ "x$tasks" = "x" ] ; then
+            if [ $verbose -eq 1 ] ; then 
+                echo executing: $@ >&2
+            fi
 
-        /bin/sh <<EOF1 > ${LogDir}${JobName}.o$$ 2> ${LogDir}${JobName}.e$$
-$@
-EOF1
-        ERR=$?
-        if [ $ERR -ne 0 ] ; then
-            cat ${LogDir}${JobName}.e$$ >&2
-            exit $ERR
-        fi
-    else
-        if [ $verbose -eq 1 ] ; then 
-            echo "Running commands in: $taskfile" >&2
-        fi
+            /bin/sh <<EOF1 > ${LogDir}${JobName}.o$$ 2> ${LogDir}${JobName}.e$$
+            $@
+            EOF1
+            ERR=$?
+            if [ $ERR -ne 0 ] ; then
+                cat ${LogDir}${JobName}.e$$ >&2
+                exit $ERR
+            fi
+        else
+            if [ $verbose -eq 1 ] ; then 
+                echo "Running commands in: $taskfile" >&2
+            fi
 
-        n=1
-        while [ $n -le $tasks ] ; do
-        line=`sed -n -e ''${n}'p' $taskfile`
-        if [ $verbose -eq 1 ] ; then 
-            echo executing: $line >&2
-        fi
-        /bin/sh <<EOF2 > ${LogDir}${JobName}.o$$.$n 2> ${LogDir}${JobName}.e$$.$n
-$line
-EOF2
-        n=`expr $n + 1`
-        done
-    fi
-    echo $$
-    ;;
+            n=1
+            while [ $n -le $tasks ] ; do
+                line=`sed -n -e ''${n}'p' $taskfile`
+                if [ $verbose -eq 1 ] ; then 
+                    echo executing: $line >&2
+                fi
+                /bin/sh <<EOF2 > ${LogDir}${JobName}.o$$.$n 2> ${LogDir}${JobName}.e$$.$n
+                $line
+                EOF2
+                n=`expr $n + 1`
+            done
+            fi
+            echo $$
+            ;;
 
 esac
 
diff --git a/utilities/scripts/CBIG_check_job_status b/utilities/scripts/CBIG_check_job_status
--- a/utilities/scripts/CBIG_check_job_status
+++ b/utilities/scripts/CBIG_check_job_status
@@ -30,51 +30,51 @@ user=`whoami`
 
 while getopts "n:l:o:" arg
 do
-        case $arg in
-             n)
-	        job=$OPTARG
-                ;;
-             l)
-	        log_file=$OPTARG
-                ;;
-             o)
-	        out_file=$OPTARG
-                ;;
-             ?)
-	        echo "Unknown argument"
-	        exit 1
-	        ;;
-        esac
+    case $arg in
+        n)
+            job=$OPTARG
+            ;;
+        l)
+            log_file=$OPTARG
+            ;;
+        o)
+            out_file=$OPTARG
+            ;;
+        ?)
+            echo "Unknown argument"
+            exit 1
+            ;;
+    esac
 done
 
 # Wait till jobs with the same name are all done
 currnode=`hostname`
 if [ "${currnode}" != "headnode" ]; then
-	echo "WARNING: ssh from $currnode to headnode ..."
-	ssh headnode "$CBIG_CODE_DIR/utilities/scripts/CBIG_wait_for_job -n ${job}"
+    echo "WARNING: ssh from $currnode to headnode ..."
+    ssh headnode "$CBIG_CODE_DIR/utilities/scripts/CBIG_wait_for_job -n ${job}"
 else
-	$CBIG_CODE_DIR/utilities/scripts/CBIG_wait_for_job -n ${job}
+    $CBIG_CODE_DIR/utilities/scripts/CBIG_wait_for_job -n ${job}
 fi
 
 if [ ! $log_file ] && [ ! $out_file ]; then
-        echo "[Warning] Both log file and output file are NOT checked."
+    echo "[Warning] Both log file and output file are NOT checked."
 fi
 
 # Check log file
 if [ $log_file ]; then
-        fail=`grep FAILED $log_file | wc -l`
-        success=`grep SUCCESS $log_file | wc -l`
-        if [ ${fail} -gt 0 ] || [ ${success} -eq 0 ]; then
-                echo "[FAILED] Job is unsuccessful. Log file: $log_file"
-                exit 1
-        fi
+    fail=`grep FAILED $log_file | wc -l`
+    success=`grep SUCCESS $log_file | wc -l`
+    if [ ${fail} -gt 0 ] || [ ${success} -eq 0 ]; then
+        echo "[FAILED] Job is unsuccessful. Log file: $log_file"
+        exit 1
+    fi
 fi
 
 # Check output files
 if [ $out_file ]; then
-        if [ ! -f ${out_file} ]; then
-                echo "[FAILED] Job is unsuccessful. Out file: $out_file does not exist."
-                exit 1
-        fi
+    if [ ! -f ${out_file} ]; then
+        echo "[FAILED] Job is unsuccessful. Out file: $out_file does not exist."
+        exit 1
+    fi
 fi
 
